<?= (!empty($this->tree->pagetitle)) ? '<h2>' . $this->tree->pagetitle . '</h2>' : ''; ?>
<?= (!empty($this->tree->description)) ? '<p>' . $this->tree->description . '</p>' : ''; ?>
<? if (count($this->documents) > 0): ?>
<?php

$dir = rtrim('/' . $this->tree->site->path, '/') . '/doc/';

foreach ($this->documents as $document) {
  if ($document->file == '') {
    echo '<h3>'.$document->title.'</h3>';
  } else {
    echo '<h3><a href="'.$dir.$document->file.'" alt="T&eacute;l&eacute;charger">'.$document->title.'</a></h3>';
  }
  echo $document->comment;
  echo '<hr />';
}

?>
<? endif; ?>

<? if (count($this->subdocuments) > 0): ?>
<?php
foreach ($this->subdocuments as $item) {
  $title = $item['title'];
  $alias = $item['alias'];
  $subdocs = $item['documents'];
  $url = $this->url(array('alias' => $alias, 'format' => 'phtml'), 'alias', true);
  echo '<h3><a href="'.$url.'">'.$title.'</a></h3><ul>';
  foreach ($subdocs as $subdoc) {
   	echo '<li>'.$subdoc->title.'</li>';
  }
  echo '</ul>';
}
?>
<? endif; ?>
