<script type="text/javascript" src="<?= $this->path ?>/fckeditor.js"></script>
<form action="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => $this->form_type, 'ext' => 'phtml', 'id' => $this->id), 'ext', true); ?>" method="post">
<input type="hidden" name="id" value="<?= $this->id ?>">
<input type="hidden" name="treeparentid" value="<?= $this->message->tree_parentid ?>">
<table border="0" width="90%">
<? if (!empty($this->id)): ?>
<tr><td class="t01"><?php echo $this->_('Id'); ?> :</td><td class="t01"><?= $this->id ?></td></tr>
<? endif; ?>
<tr><td class="t01"><?= $this->formLabel('date', $this->_('Date')); ?> : </td><td><?= $this->formText('date', $this->message->date); ?></td></tr>
<tr><td class="t01"><?= $this->formLabel('title', $this->_('Title')); ?> : </td><td><?= $this->formText('title', $this->message->title, array('size' => 40)); ?></td></tr>
<tr><td class="t01"><?= $this->formLabel('parentid', $this->_('Read more')); ?> : </td><td>
<?php echo $this->selectTree('parentid', $this->message->tree_id) ?></td></tr>
<tr><td class="t01"><?= $this->formLabel('content', $this->_('Content')); ?> : </td><td><?= $this->formTextarea('content', $this->message->content, array('rows' => 20, 'cols' => 60)); ?></td></tr>
<tr><td colspan="2" align="center"><?= $this->formSubmit('btn', $this->_(ucfirst($this->form_type))); ?></td></tr>
</table></form>
<br/>
<p class="t01" style="font-size: 12px;">
	<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tree', 'action' => 'edit', 'id' => $this->message->tree_parentid), 'ext'); ?>"><?php echo $this->_('Return') ?></a>
</p>
<script type="text/javascript">
      window.onload = function()
      {
        var oFCKeditor = new FCKeditor( 'content' ) ;
        oFCKeditor.BasePath = "<?= $this->path ?>/" ;
        oFCKeditor.Width = 600;
		oFCKeditor.Height = 400;
        oFCKeditor.ReplaceTextarea() ;
      }
</script>