<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="keywords" content="extjs,ext,ux,javascript,library,web development,web design,dhtml,widget,webdev,component,control,tree,file,gui,interface,effect,example,demo,download,howto,yui-ext,theme,aero,vista,skin,animation">
	<title><?php echo $this->request->getDomainName (); ?> - Administration</title>
	<link rel="stylesheet" type="text/css" href="<?= $this->path ?>/javascripts/extjs/resources/css/ext-all.css">
	<link rel="stylesheet" type="text/css" href="<?= $this->path ?>/stylesheets/uploadform.css">

	<link rel="stylesheet" type="text/css" href="<?= $this->path ?>/stylesheets/filetree.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->path ?>/stylesheets/rged.css">
    <link id="theme" rel="stylesheet" type="text/css" href="<?= $this->path ?>/javascripts/extjs/resources/css/xtheme-default.css">
	<link rel="shortcut icon" href="/img/silk/icons/page_white_stack.png" type="image/png">
	<script type="text/javascript">
		var path = "<?= $this->path ?>";
		var basename = "<?= $this->url(array(), 'default', true); ?>";
	</script>
	<script type="text/javascript" src="<?= $this->path ?>/javascripts/extjs/adapter/ext/ext-base.js"></script>
	<script type="text/javascript" src="<?= $this->path ?>/javascripts/extjs/ext-all.js"></script>
    <script type="text/javascript" src="<?= $this->path ?>/javascripts/Ext.ux.UploadForm.js"></script>
    <script type="text/javascript" src="<?= $this->path ?>/javascripts/Ext.ux.FileTreePanel.js"></script>
    <script type="text/javascript" src="<?= $this->path ?>/javascripts/rged.js"></script>
    <script type="text/javascript" src="<?= $this->path ?>/javascripts/history.js"></script>
<style type="text/css">
#acc-ct {
	width: 240px;
	position: relative;
}
#acc-wrap {
	border: 1px solid silver;
	background-color: white;
}
#adsense-top, #adsense-bottom {
	margin: 10px;
}
.x-dock-panel .x-dock-panel-body {
	background-color: #ffffc8;
}
</style>
</head>

<body>
    <div id="menu"></div>
    <div id="tree"></div>
    <div id="grid"></div>
    <div id="menu-div"></div>
    <div id="tree-div"></div>
    <div id="grid-div"></div>
    </body>
</html>

