
<h1><img width="16" height="16" border="0"
	title="<?php
echo $this->_('user')?>"
	alt="<?php
echo $this->_('user')?>" class="folder" border="0"
	src="<?php
echo $this->path;
?>/images/icons/user.png" />&nbsp;<?php
echo $this->_('User')?></h1>
<table cellpadding="0" cellspacing="0" width="100%" class="list">
	<thead>
		<tr>
			<th style="width: 16px">&nbsp;</th>
			<th style="width: 100px"><?php
echo $this->_('User name')?></th>
			<th style="width: 100px"><?php
echo $this->_('First name')?></th>
			<th style="width: 100px"><?php
echo $this->_('Last name')?></th>
			<th style="width: 100px"><?php
echo $this->_('E-mail')?></th>
			<th style="width: 40px" align="right"><?php
echo $this->_('Action')?></th>
		</tr>
	</thead>
	<?php
foreach ($this->users_list as $user) :
    ?>
		<tr>
		<td>
			<?php
    echo $this->escape($user->id);
    ?>
			</td>
		<td>
			<?php
    echo $this->escape($user->login);
    ?>
			</td>
		<td>
			<?php
    echo $this->escape($user->firstname);
    ?>
			</td>
		<td>
			<?php
    echo $this->escape($user->lastname);
    ?>
			</td>
		<td>
			<?php
    echo $this->escape($user->email);
    ?>
			</td>
		<td align="right"><a
			href="<?php
    echo $this->url(array('controller' => 'user' , 'action' => 'edit' , 'format' => 'phtml' , 'id' => $user->id), 'format', true);
    ?>">
		<img width="16" height="16" border="0"
			title="<?php
    echo $this->_('Edit')?>"
			alt="<?php
    echo $this->_('Edit')?>" class="folder"
			src="<?php
    echo $this->path;
    ?>/images/icons/user_edit.png" /> </a> <a
			href="<?php
    echo $this->url(array('controller' => 'user' , 'action' => 'delete' , 'format' => 'phtml' , 'id' => $user->id), 'format', true);
    ?>"
			onclick="return confirm('<?php
    echo $this->escape($this->_('Do you really want to delete this user?'));
    ?>');">
		<img width="16" height="16" border="0"
			title="<?php
    echo $this->_('Delete')?>"
			alt="<?php
    echo $this->_('Delete')?>" class="folder"
			src="<?php
    echo $this->path;
    ?>/images/icons/user_delete.png" /> </a>
		</td>
	</tr>
	<?php
endforeach;
?>
	</table>
<br />
<a href="<?php
echo $this->url(array('controller' => 'user' , 'action' => 'add' , 'format' => 'phtml'), 'format', true);
?>" class="jimw-icon icon-user-add">
    <?php echo $this->_('Add'); ?>
</a>
<hr />
<a
	href="<?php
echo $this->url(array('controller' => 'user'), 'format', true);
?>" class="jimw-return">
<?php
echo $this->_('Return');
?></a>