<h1><img width="16" height="16" border="0"
	title="<?php
echo $this->_('Page')?>"
	alt="<?php
echo $this->_('Page')?>" class="folder" border="0"
	src="<?php
echo $this->path;
?>/images/icons/page_white_edit.png" />&nbsp;<?php
echo $this->_('page')?></h1>
<?php
foreach ($this->flashmessenger as $message)
    echo $message . '<br />';
?>
<?php
 $this->accordionPane('tree_accordion', $this->form->render(), array('title' => 'Information générale'));
 $active = 0;
 if (isset($this->edit_form)) {
     $this->accordionPane('tree_accordion', $this->edit_form, array('title' => 'Module ' . $this->tree->module_path));
     $active = 1;
 }
 echo $this->accordionContainer('tree_accordion', array('active' => $active, 'fillSpace' => true));
?>
<br style="clear: both;" />
<p class="t01" style="font-size: 12px;">
<a href="<?php
echo $this->url(array('controller' => 'tree' , 'action' => 'list' , 'format' => 'phtml'), 'format', true);
?>" class="jimw-return">
    <?php echo $this->_('Return'); ?>
</a>
</p>
<?php ?>