<?php
foreach ($this->flashmessenger as $message)
    echo $message . '<br />';
?>
<p class="t01"><a
	href="<?php
echo $this->url(array('controller' => 'tree' , 'action' => 'list' , 'format' => 'phtml'), 'format', true);
?>">
<img width="16" height="16" border="0"
	title="<?php
echo $this->_('Return')?>"
	alt="<?php
echo $this->_('Return')?>" class="folder"
	src="<?php
echo $this->path;
?>/images/icons/arrow_undo.png" />&nbsp;<?php
echo $this->_('Return');
?></a>
</p>