<?php
$path = $this->path;

$baseurl = $this->request->getBaseUrl();
function list_tree($list, $view, $path, $baseurl) {

?>
<ul style='list-style:none; margin-left: 15px; padding:0;'>
<?php
	$item = 0;
	$length = count($list);
	foreach ($list as $tree):
		?>
		<li>
			<img src="<?= $path ?>/images/dot_g.gif" width="5" height="5" alt="" border="0" class="absmiddle"> <?= $tree->order?>)
				<?= $tree->menutitle?> ( <?= $tree->alias?> : <?= $tree->id?>)
				<a href="<?php echo $view->url(array('controller' => 'tree', 'action' => 'edit', 'ext' => 'phtml', 'id' => $tree->id), 'ext', true); ?>">
				<img src="<?= $path ?>/images/edit.gif" width="16" height="16" alt="<?php echo $view->_('Edit'); ?>" title="<?php echo $view->_('Edit'); ?>" border="0" class="absmiddle" /></a> -
				<a href="<?php echo $view->url(array('controller' => 'tree', 'action' => 'delete', 'ext' => 'phtml', 'id' => $tree->id), 'ext', true); ?>" onclick="return confirm('<?php echo $view->escape($view->_('Do you realy want to Delete this Page ?')); ?>');">
				<img src="<?= $path ?>/images/delete.gif" width="16" height="16" alt="<?php echo $view->_('Delete'); ?>" title="<?php echo $view->_('Delete'); ?>" border="0" class="absmiddle" /></a>

				<?php
					if ($item > 0) {
				?>
					<a href="<?php echo $view->url(array('controller' => 'tree', 'action' => 'move', 'dir' => 'up', 'ext' => 'phtml', 'id' => $tree->id), 'ext', true); ?>">
					<img src="<?= $path ?>/images/icons/arrow_up.png" width="16" height="16" alt="<?php echo $view->_('Move Up'); ?>" title="<?php echo $view->_('Move Up'); ?>"  border="0" class="absmiddle" /></a>
				<?php
					}
					else {
				?>
					<img src="<?= $path ?>/images/px1.gif" width="16" height="1" alt="" border="0" class="absmiddle" />
				<?php
					}
					if ($item < $length - 1) {
				?>
					<a href="<?php echo $view->url(array('controller' => 'tree', 'action' => 'move', 'dir' => 'down', 'ext' => 'phtml', 'id' => $tree->id), 'ext', true); ?>">
					<img src="<?= $path ?>/images/icons/arrow_down.png" width="16" height="16" alt="<?php echo $view->_('Move Down'); ?>" title="<?php echo $view->_('Move Down'); ?>"  border="0" class="absmiddle" /></a>
				<?php
					}
					else {
				?>
					<img src="<?= $path ?>/images/px1.gif" width="16" height="1" alt="" border="0" class="absmiddle" />
				<?php
					}
					$item++;
				?>
				</li>
		<?php
		if ($tree->hasChildren ()) {
			list_tree($tree->getChildren (), $view, $path, $baseurl);
		}
		?>

		<?php
	endforeach;
?>
</ul>
<?php
}
?>
<p class="t01"><?php echo $this->_('Edit the website') ?></p>
<?php
foreach ($this->flashmessenger as $message)
echo $message . '<br />'; ?>
<p class="list">
<?php
list_tree($this->list_tree, $this, $path, $baseurl);
?>
</p>
<p class="t01"><a href="<?php echo $this->url(array('controller' => 'tree', 'action' => 'add', 'ext' => 'phtml'), 'ext', true); ?>"><?php echo $this->_('Add new Page') ?></a></p>
