<?= (!empty($this->tree->description)) ? '<p>' . $this->tree->description . '</p>' : ''; ?>

<? if (!empty($this->list_article)): ?>
<ul>
<? foreach ($this->list_article as $article): ?>
<li><a href="<?= $this->url(array('alias' => $article->alias), 'alias'); ?>"><?= $this->escape($article->menutitle) ?></a><br /><?= $this->escape($this->troncate($article->description)) ?></li>
<? endforeach; ?>
</ul>
<? else: ?>
<p>Article not found</p>
<? endif; ?>