<div class="sidenav">
			<h1><? echo $this->_('User'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'list', 'format' => 'phtml'), 'format', true); ?>">
				<img width="16" height="16" border="0" title="<?php echo $this->_('List') ?>" alt="<?php echo $this->_('List') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/user.png"/>&nbsp;<? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add', 'format' => 'phtml'), 'format', true); ?>">
				<img width="16" height="16" border="0" title="<?php echo $this->_('Add') ?>" alt="<?php echo $this->_('Add') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/user_add.png"/>&nbsp;<? echo $this->_('Add'); ?></a></li>
			</ul>
			</ul>
			<h1><? echo $this->_('Group'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'list', 'format' => 'phtml'), 'format', true); ?>">
				<img width="16" height="16" border="0" title="<?php echo $this->_('List') ?>" alt="<?php echo $this->_('List') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/group.png"/>&nbsp;<? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'add', 'format' => 'phtml'), 'format', true); ?>">
				<img width="16" height="16" border="0" title="<?php echo $this->_('Add') ?>" alt="<?php echo $this->_('Add') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/group_add.png"/>&nbsp;<? echo $this->_('Add'); ?></a></li>
			</ul>
			<h1><? echo $this->_('Permission'); ?></h1>
			<ul>
<!-- 				<li><a href="<?php echo $this->url(array('controller' => 'perm', 'action' => 'list', 'format' => 'phtml'), 'format', true); ?>">
				<img width="16" height="16" border="0" title="<?php echo $this->_('List') ?>" alt="<?php echo $this->_('List') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/key.png"/>&nbsp;<? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'perm', 'action' => 'add', 'format' => 'phtml'), 'format', true); ?>">
				<img width="16" height="16" border="0" title="<?php echo $this->_('Add') ?>" alt="<?php echo $this->_('Add') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/key_add.png"/>&nbsp;<? echo $this->_('Add'); ?></a></li> -->
			</ul>
			<br />
			<br />
			<br />
</div>