<h2>Contenu de votre panier</h2>
<?php if (count($this->score) == 0 && count($this->albumscore) == 0 && 
          count($this->music) == 0 && count($this->albummusic) == 0): ?>
<p>Votre panier est vide.</p>
<?php else: ?>
<?php $sum = 0; $readonly = true; ?>
<form method="post" action="<?php echo $this->url(array('module' => 'shop', 'controller' => 'basket', 'action' => 'confirm'), 'format', true); ?>">
<?php include_once('list.phtml'); ?>
<p>Total : <b><?php echo $sum ?> &euro;</b></p>

<h3>Adresse de facturation</h3>
<?php if ($this->websalto): ?>
<p>Civilité : <select name="civilite">
  <option value="Monsieur" selected="selected">Monsieur</option>
  <option value="Madame">Madame</option>
  <option value="Mademoiselle">Mademoiselle</option>
</select></p>
<p>Nom : <input type="text" name="name" maxlength="30" /></p>
<p>Prénom : <input type="text" name="firstname" maxlength="30" /></p>
<p>Adresse : <input type="text" name="adresse" /></p>
<p>Code postal : <input type="text" name="codepostal" /></p>
<p>Ville : <input type="text" name="ville" /></p>
<p>Pays : <select name="pays" >
  <option value="Afrique du Sud">Afrique du Sud</option>
  <option value="Afghanistan ">Afghanistan </option>
  <option value="Albanie">Albanie</option>
  <option value="Algerie">Algerie</option>
  <option value="Allemagne">Allemagne</option>
  <option value="American Samoa">American Samoa </option>
  <option value="Principauté d'Andorre (">Andorre (Principauté d')</option>
  <option value="Angola">Angola </option>
  <option value="Anguilla">Anguilla </option>
  <option value="Antarctique">Antarctique</option>
  <option value="Antigua and Barbuda">Antigua and Barbuda </option>
  <option value="Antilles Néerlandaises">Antilles Néerlandaises</option>
  <option value="Argentine">Argentine</option>
  <option value="Arménie">Arménie</option>
  <option value="Aruba">Aruba </option>
  <option value="Australie">Australie</option>
  <option value="Autriche">Autriche</option>
  <option value="Azerbaijan">Azerbaijan </option>
  <option value="Bahamas">Bahamas </option>
  <option value="Bahrain">Bahrain </option>
  <option value="Bangladesh">Bangladesh </option>
  <option value="Barbades">Barbades</option>
  <option value="Belarus">Belarus </option>
  <option value="Belgique">Belgique</option>
  <option value="Belize">Belize </option>
  <option value="Benin">Benin </option>
  <option value="Bermudes">Bermudes</option>
  <option value="Bhutan">Bhutan </option>
  <option value="Bolivie">Bolivie</option>
  <option value="Bosnie-Herzegovine">Bosnie-Herzegovine</option>
  <option value="Botswana">Botswana </option>
  <option value="Ile Bouvet">Bouvet (Ile)</option>
  <option value="Brésil">Brésil</option>
  <option value="Territoires Britanniques de l'Océan Indien">Territoires Britanniques de l'Océan Indien</option>
  <option value="Brunei Darussalam">Brunei Darussalam </option>
  <option value="Bulgarie">Bulgarie</option>
  <option value="Burkina Faso">Burkina Faso </option>
  <option value="Burundi">Burundi </option>
  <option value="Cambodge">Cambodge</option>
  <option value="Cameroun">Cameroun</option>
  <option value="Canada">Canada </option>
  <option value="Cap Vert">Cap Vert</option>
  <option value="Iles Caïman">Caïman (iles)</option>
  <option value="Chili">Chili</option>
  <option value="Chine">Chine</option>
  <option value="Christmas Island">Christmas Island </option>
  <option value="Chypre">Chypre</option>
  <option value="Cocos Islands">Cocos Islands </option>
  <option value="Colombie">Colombie</option>
  <option value="Comores">Comores</option>
  <option value="Congo">Congo </option>
  <option value="Cook Islands">Cook Islands </option>
  <option value="Corée (République démocratique de)">Corée (République démocratique de)</option>
  <option value="Corée (du Sud)">Corée (du Sud)</option>
  <option value="Costa Rica">Costa Rica </option>
  <option value="Cote D'ivoire">Cote D'ivoire </option>
  <option value="Croatie">Croatie</option>
  <option value="Cuba">Cuba </option>
  <option value="Danemark ">Danemark</option>
  <option value="Djibouti">Djibouti </option>
  <option value="Dominique">Dominique</option>
  <option value="Timor Est">Timor Est</option>
  <option value="Equateur">Equateur</option>
  <option value="Egypte">Egypte </option>
  <option value="El Salvador">El Salvador </option>
  <option value="Guinée Equatoriale">Guinée Equatoriale</option>
  <option value="Erytrée">Erytrée</option>
  <option value="Espagne">Espagne</option>
  <option value="Estonie">Estonie</option>
  <option value="Etats-Unis d'Amérique">Etats-Unis d'Amérique</option>
  <option value="Ethiopie">Ethiopie</option>
  <option value="Iles Falkland ">Falkland (Iles)</option>
  <option value="Iles Faroe">Faroe (iles)</option>
  <option value="Fiji">Fiji </option>
  <option value="Finlande">Finlande</option>
  <option value="France" selected="selected">France</option>
  <option value="Territoires français du Sud">Territoires français du Sud</option>
  <option value="Gabon">Gabon </option>
  <option value="Gambie">Gambie </option>
  <option value="Georgie">Georgie </option>
  <option value="Ghana">Ghana </option>
  <option value="Gibraltar">Gibraltar </option>
  <option value="Greece">Greece </option>
  <option value="Greenland">Greenland </option>
  <option value="Grenada">Grenada </option>
  <option value="Guadeloupe">Guadeloupe </option>
  <option value="Guam">Guam </option>
  <option value="Guatemala">Guatemala </option>
  <option value="Guinée">Guinée</option>
  <option value="Guinea-Bissau">Guinea-Bissau </option>
  <option value="Guinée Française">Guinée Française</option>
  <option value="Guyana">Guyana </option>
  <option value="Haiti">Haiti </option>
  <option value="Heard Island And Mcdonald Islands">Heard Island And Mcdonald Islands </option>
  <option value="Honduras">Honduras </option>
  <option value="Hong Kong">Hong Kong </option>
  <option value="Hongrie">Hongrie</option>
  <option value="Islande">Islande</option>
  <option value="Inde">Inde </option>
  <option value="Indonesie">Indonesie </option>
  <option value="Iran">Iran </option>
  <option value="Iraq">Iraq </option>
  <option value="Irelande">Irelande </option>
  <option value="Israël">Israël </option>
  <option value="Italie">Italie</option>
  <option value="Jamaïque">Jamaïque</option>
  <option value="Japon">Japon</option>
  <option value="Jordanie">Jordanie</option>
  <option value="Kazakhstan">Kazakhstan </option>
  <option value="Kenya">Kenya </option>
  <option value="Kiribati">Kiribati </option>
  <option value="Kowait">Kowait</option>
  <option value="Kyrgyzstan">Kyrgyzstan </option>
  <option value="République démocratique du Laos">Laos (République démocratique du)</option>
  <option value="Latvia">Latvia </option>
  <option value="Lebanon">Lebanon </option>
  <option value="Lesotho">Lesotho </option>
  <option value="Liberia">Liberia </option>
  <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya </option>
  <option value="Liechtenstein">Liechtenstein </option>
  <option value="Lithuanie">Lithuanie </option>
  <option value="Luxembourg">Luxembourg </option>
  <option value="Macau">Macau </option>
  <option value="Macedoine">Macedoine</option>
  <option value="Madagascar">Madagascar </option>
  <option value="Malawi">Malawi </option>
  <option value="Malaysia">Malaysia </option>
  <option value="Maldives">Maldives </option>
  <option value="Mali">Mali </option>
  <option value="Malta">Malta </option>
  <option value="Marshall Islands">Marshall Islands </option>
  <option value="Martinique">Martinique </option>
  <option value="Mauritanie">Mauritanie </option>
  <option value="Mauritius">Mauritius </option>
  <option value="Mayotte">Mayotte </option>
  <option value="Mexico">Mexico </option>
  <option value="Micronesie">Micronesie </option>
  <option value="Moldavie">Moldavie</option>
  <option value="Monaco">Monaco </option>
  <option value="Mongolie">Mongolie </option>
  <option value="Montserrat">Montserrat </option>
  <option value="Morocco">Morocco </option>
  <option value="Mozambique">Mozambique </option>
  <option value="Myanmar">Myanmar </option>
  <option value="Namibie">Namibie </option>
  <option value="Nauru">Nauru </option>
  <option value="Nepal">Nepal </option>
  <option value="Nouvelle Caledonie">Nouvelle Caledonie</option>
  <option value="Nouvelle Zélande">Nouvelle Zélande</option>
  <option value="Nicaragua">Nicaragua </option>
  <option value="Niger">Niger </option>
  <option value="Nigeria">Nigeria </option>
  <option value="Niue">Niue </option>
  <option value="Norfolk Island">Norfolk Island </option>
  <option value="Northern Mariana Islands">Northern Mariana Islands </option>
  <option value="Norvège">Norvège</option>
  <option value="Oman">Oman </option>
  <option value="Ouganda">Ouganda</option>
  <option value="Pakistan">Pakistan </option>
  <option value="Palau">Palau </option>
  <option value="Panama">Panama </option>
  <option value="Papouasie Nouvelle Guinée">Papouasie Nouvelle Guinée</option>
  <option value="Paraguay">Paraguay </option>
  <option value="Pays-Bas">Pays-Bas</option>
  <option value="Pérou">Pérou</option>
  <option value="Philippines">Philippines </option>
  <option value="Pitcairn">Pitcairn </option>
  <option value="Pologne">Pologne</option>
  <option value="Polynésie Française">Polynésie Française</option>
  <option value="Portugal">Portugal </option>
  <option value="Puerto Rico">Puerto Rico </option>
  <option value="Qatar">Qatar </option>
  <option value="République Centrale d'Afrique">République Centrale d'Afrique</option>
  <option value="Republique Dominicaine">Republique Dominicaine</option>
  <option value="Réunion">Réunion</option>
  <option value="Roumanie">Roumanie</option>
  <option value="Russe (Federation)">Russe (Federation)</option>
  <option value="Rwanda">Rwanda </option>
  <option value="Sainte Hélène">Sainte Hélène</option>
  <option value="Saint Kitts and Nevis">Saint Kitts and Nevis </option>
  <option value="Sainte Lucie ">Sainte Lucie</option>
  <option value="Saint Pierre et Miquelon">Saint Pierre et Miquelon</option>
  <option value="Saint Vincent et les Grenadines">Saint Vincent et les Grenadines</option>
  <option value="Samoa">Samoa </option>
  <option value="San Marino">San Marino </option>
  <option value="Sao Tome and Principe">Sao Tome and Principe </option>
  <option value="Arabie Saoudite">Arabie Saoudite</option>
  <option value="Senegal">Senegal </option>
  <option value="Seychelles">Seychelles </option>
  <option value="Sierra Leone">Sierra Leone </option>
  <option value="Singapour">Singapour</option>
  <option value="Slovaquie">Slovaquie</option>
  <option value="Slovenie">Slovenie</option>
  <option value="Iles Salomon">Salomon (Iles)</option>
  <option value="Somalie">Somalie</option>
  <option value="South Georgia and Sandwich Islands">South Georgia and Sandwich Islands </option>
  <option value="Sri Lanka">Sri Lanka </option>
  <option value="Sudan">Sudan </option>
  <option value="Suriname">Suriname </option>
  <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen </option>
  <option value="Swaziland">Swaziland </option>
  <option value="Suède">Suède</option>
  <option value="Suisse">Suisse</option>
  <option value="République Arabe de Syrie">Syrie (République Arabe de)</option>
  <option value="Taiwan">Taiwan </option>
  <option value="Tajikistan">Tajikistan </option>
  <option value="Tanzanie">Tanzanie</option>
  <option value="Tchad ">Tchad</option>
  <option value="Tchécoslovaquie">Tchécoslovaquie</option>
  <option value="Thailande">Thailande</option>
  <option value="Togo">Togo </option>
  <option value="Tokelau">Tokelau </option>
  <option value="Tonga">Tonga </option>
  <option value="Trinidad and Tobago">Trinidad and Tobago </option>
  <option value="Tunisie">Tunisie</option>
  <option value="Turquie">Turqiue</option>
  <option value="Turkmenistan">Turkmenistan </option>
  <option value="Turks and Caicos Islands">Turks and Caicos Islands </option>
  <option value="Tuvalu">Tuvalu </option>
  <option value="Ukraine">Ukraine </option>
  <option value="United Arab Emirates">United Arab Emirates </option>
  <option value="United Kingdom">United Kingdom </option>
  <option value="United States Minor Outlying Islands">United States Minor Outlying Islands </option>
  <option value="Uruguay">Uruguay </option>
  <option value="Uzbekistan">Uzbekistan </option>
  <option value="Vanuatu">Vanuatu </option>
  <option value="Etat du Vatican">Vatican (Etat du)</option>
  <option value="Venezuela">Venezuela </option>
  <option value="Vietnam">Vietnam </option>
  <option value="Iles Vierges Britaniques">Vierges (Iles) -Britaniques-</option>
  <option value="Iles Vierges (U.S.)">Vierge (iles) -U.S. -</option>
  <option value="Iles Wallis et Futuna">Wallis et Futuna (iles)</option>
  <option value="Western Sahara">Western Sahara </option>
  <option value="Yemen">Yemen </option>
  <option value="Yougoslavie">Yougoslavie</option>
  <option value="Zaire">Zaire </option>
  <option value="Zambie">Zambie</option>
  <option value="Zimbabwe">Zimbabwe </option>
</select></p>
<?php else: ?>
<p>Nom : <input type="text" name="name" maxlength="30" /></p>
<p>Prénom : <input type="text" name="firstname" maxlength="30" /></p>
<?php endif; ?>
<p>Email : <input type="text" name="email" /><small> (pour recevoir les partitions)</small></p>
<p>Mode de paiement : 
  <input type="radio" name="paymentmode" value="CB" id="CB" /> <label for="CB"><img src="<?php echo $this->path; ?>/shop/cb.gif" border="0" /></label>
  &nbsp; <input type="radio" name="paymentmode" value="VISA" id="VISA" checked="checked" /> <label for="VISA"><img src="<?php echo $this->path; ?>/shop/visa.gif" border="0" /></label>
  &nbsp; <input type="radio" name="paymentmode" value="MASTERCARD" id="MASTERCARD" /> <label for="MASTERCARD"><img src="<?php echo $this->path; ?>/shop/mastercard.gif" border="0" /></label>
</p>
<input type="submit" value="Confirmer et payer en ligne" />
</form>
<?php endif; ?>