<h2>Contenu de votre commande</h2>
<?php if (count($this->score) == 0 && count($this->albumscore) == 0 && 
          count($this->music) == 0 && count($this->albummusic) == 0): ?>
<p>Votre commande est vide.</p>
<?php else: ?>
<?php $sum = 0; $readonly = true; ?>
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
<?php include_once('list.phtml'); ?>
<p>Total : <b><?php echo $sum ?> &euro;</b></p>

<p>Nom : <?php echo $this->item->name; ?></p>
<p>Prénom : <?php echo $this->item->firstname; ?></p>
<p>Email : <?php echo $this->item->email; ?></p>

<p><b>Merci de conserver la référence de la transaction : <?php echo $this->orderid; ?></b></p>

<?php $paymentmode = 'sogenactif'; ?>

<?php if ($paymentmode == 'paypal'): ?>

<p>Cliquez sur le bouton <b>Payer</b> ci-dessous pour procéder au paiement. Ensuite, sur la page qui va s'afficher, cliquez sur le lien <b>Continuer</b> en bas à gauche, qui se trouve en dessous de <b>Vous n'avez pas de compte PayPal ?</b></p>

<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="clients@logisim.fr">
<input type="hidden" name="lc" value="FR">
<input type="hidden" name="item_name" value="Partitions sur le site du MEJ">
<input type="hidden" name="item_number" value="<?php echo $this->orderid; ?>">
<input type="hidden" name="amount" value="<?php echo $sum; ?>">
<input type="hidden" name="currency_code" value="EUR">
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="rm" value="1">
<input type="hidden" name="return" value="http://www.mej.fr">
<input type="hidden" name="cancel_return" value="http://www.mej.fr">
<input type="hidden" name="bn" value="PP-BuyNowBF:btn_paynowCC_LG.gif:NonHosted">
<input type="image" src="https://www.paypal.com/fr_FR/FR/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="">
<img alt="" border="0" src="https://www.paypal.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
</form>

<?php elseif ($paymentmode == 'sogenactif'): ?>

<?php
	$parm = "merchant_id=014213245611111";
	$parm = "$parm merchant_country=fr";
	$parm = "$parm amount=".(int)($sum*100);
	$parm = "$parm transaction_id=".$this->orderid;
	$parm = "$parm currency_code=978"; // EURO
	$parm = "$parm pathfile=/home/sogenactif/param/pathfile";
	$parm = "$parm normal_return_url=http://".$_SERVER['HTTP_HOST'].$this->url(array('module' => 'shop', 'controller' => 'basket', 'action' => 'response'));
	$parm = "$parm cancel_return_url=http://".$_SERVER['HTTP_HOST'].$this->url(array('module' => 'shop', 'controller' => 'basket', 'action' => 'response'));
	$parm = "$parm automatic_response_url=http://".$_SERVER['HTTP_HOST'].$this->url(array('module' => 'shop', 'controller' => 'basket', 'action' => 'autoresponse'));
	$path_bin = "/home/sogenactif/bin/request";
	$result = exec("$path_bin $parm");
	$tableau = explode ("!", "$result");
	$code = $tableau[1];
	$error = $tableau[2];
	$message = $tableau[3];
	
  if (( $code == "" ) && ( $error == "" )) echo "Erreur : exécutable non trouvé ($path_bin)";
	elseif ($code != 0) echo "Erreur : $error<br>";
	else {
		echo $message.'<br>';
		echo $error; // Debug
	}

?>

<?php endif; ?>

<?php endif; ?>