<div class="sidenav">

			<h1><? echo $this->_('Module'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Install'); ?></a></li>
			</ul>
</div>