<div class="content">
<h1><img width="16" height="16" border="0" title="<?php echo $this->_('Update Database') ?>" alt="<?php echo $this->_('Update Database') ?>" class="folder" border="0" src="<?php echo $this->path; ?>/images/icons/database_refresh.png"/>&nbsp;<?php echo $this->_('Update Database') ?></h1>
<?php
	echo $this->content;
?>
</div>
<?php echo $this->render('system/menu.phtml'); ?>