<form action="<?php echo $this->url(array('controller' => 'tree', 'action' => $this->form_type, 'ext' => 'phtml'), 'ext', true); ?>" method="post">
<input type="hidden" name="id" value="<?= $this->id ?>">
<input type="hidden" name="sub" value="1">
<table border="0" width="90%">
<? if (!empty($this->id)): ?>
<tr><td class="t01"><?php echo $this->_('Id'); ?> :</td><td class="t01"><?= $this->id ?></td></tr>
<? endif; ?>
<tr><td class="t01"><?php echo $this->_('Title'); ?> :</td><td><input type="text" name="pagetitle" size="40" value="<?= $this->tree->pagetitle?>"></td></tr>
<tr><td class="t01"><?php echo $this->_('Menu Title'); ?> :</td><td><input type="text" name="menutitle" size="40" value="<?= $this->tree->menutitle?>"></td></tr>
<tr><td class="t01"><?php echo $this->_('Menu Order'); ?> :</td><td><input type="text" name="order" size="40" value="<?= $this->tree->order?>"></td></tr>
<tr><td class="t01"><?php echo $this->_('Parent'); ?> :</td><td>
<?php echo $this->selectTree('parentid', $this->tree->parentid) ?>
</td></tr>
<tr><td class="t01"><?php echo $this->_('Alias'); ?> : </td><td><input type="text" name="alias" size="40" value="<?= $this->tree->alias?>"></td></tr>
<?php
	if (isset($this->modules)):
?>
<tr><td class="t01"><?php echo $this->_('Module Type'); ?> : </td><td><select name="module">
<?php
	foreach ($this->modules as $module)
		echo '<option value="', $module->id,'">',$module->name,'</option>';
?>
</select></td></tr>
<?php
	endif;
?>
<tr><td class="t01"><?php echo $this->_('Description'); ?> : </td><td><textarea name="description" rows="4" cols="37"><?= $this->tree->description?></textarea></td></tr>
<tr><td colspan="2" align="center"><input type="submit" name="btn" value="<?php echo $this->_(ucfirst($this->form_type))?>"></td>
</tr>
</table></form>
<br/>
<p class="t01" style="font-size: 12px;">
<a href="<?php echo $this->url(array('controller' => 'tree', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><?php echo $this->_('Return') ?></a>
</p>