<form action="<?php echo $this->url(array('controller' => 'tree', 'action' => $this->form_type, 'ext' => 'phtml'), 'ext', true); ?>" method="post">
<input type="hidden" name="id" value="<?= $this->id ?>">
<input type="hidden" name="sub" value="1">
<table border="0" width="90%">
<? if (!empty($this->id)): ?>
<tr><td class="t01"><?php echo $this->_('Id'); ?> :</td><td class="t01"><?= $this->id ?></td></tr>
<? endif; ?>
<tr><td class="t01"><?= $this->formLabel('title', $this->_('Title')); ?> :</td><td><?= $this->formText('pagetitle', $this->tree->pagetitle, array('size' => 40)); ?></td></tr>
<tr><td class="t01"><?= $this->formLabel('menutitle', $this->_('Menu Title')); ?> :</td><td><?= $this->formText('menutitle', $this->tree->menutitle, array('size' => 40)); ?></td></tr>
<tr><td class="t01"><?= $this->formLabel('parentid', $this->_('Parent')); ?> :</td><td>
<?php echo $this->selectTree('parentid', $this->tree->parentid) ?>
</td></tr>
<tr><td class="t01"><?= $this->formLabel('alias', $this->_('Alias')); ?> : </td><td><?= $this->formText('alias', $this->tree->alias, array('size' => 40)); ?></td></tr>
<?php
	if (isset($this->modules)):
?>
<tr><td class="t01"><?= $this->formLabel('module', $this->_('Module Type')); ?> : </td><td><select name="module">
<?php
	foreach ($this->modules as $module)
		echo '<option value="', $module->id,'">',$module->name,'</option>';
?>
</select></td></tr>
<?php
	endif;
?>
<tr><td class="t01"><?= $this->formLabel('description', $this->_('Description')); ?> : </td><td><?= $this->formTextarea('description', $this->tree->description, array('rows' => 4, 'cols' => 40)); ?></td></tr>
<tr><td colspan="2" align="center"><?= $this->formSubmit('btn', $this->_(ucfirst($this->form_type))); ?></td>
</tr>
</table></form>
<br/>
<p class="t01" style="font-size: 12px;">
<a href="<?php echo $this->url(array('controller' => 'tree', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><?php echo $this->_('Return') ?></a>
</p>