	<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th style="width:32px">&nbsp;</th>
			<th style="width:200px"><?php echo $this->_('Title') ?></th>
			<th style="width:200px"><?php echo $this->_('Date') ?></th>
			<th style="width:40px" align="right"><?php echo $this->_('Action') ?></th>
		</tr>
	</thead>
	<?php
		foreach ($this->messages_list as $message): ?>
		<tr>
			<td>
			<?php echo $this->escape($message->id); ?></td>
			<td>
			<?php echo $this->escape($message->title); ?>
			</td>
			<td>
			<?php echo $this->escape($message->date); ?>
			</td>
			<td align="right">
				<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'edit', 'ext' => 'phtml', 'id' => $message->id), 'ext', true); ?>">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Edit') ?>" alt="<?php echo $this->_('Edit') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/pencil.png"/>
				</a>
				<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'delete', 'ext' => 'phtml', 'id' => $message->id), 'ext', true); ?>"  onclick="return confirm('<?php echo $this->escape($this->_('Do you really want to delete this message ?')); ?>');">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Delete') ?>" alt="<?php echo $this->_('Delete') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/cross.png"/>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
<br />
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'add', 'id' => $this->id, 'ext' => 'phtml'), 'ext', true); ?>"><?php echo $this->_('Add'); ?></a>
<hr />
<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'tree', 'action' => 'list'), 'ext', true); ?>"><?php echo $this->_('Return'); ?></a>