<?php
$tabext = array(
  'bz2' => 'application/x-bzip2',
  'chm' => 'application/vnd.ms-htmlhelp',
  'doc' => 'application/msword',
  'eps' => 'application/postscript',
  'jpg' => 'image/jpeg',
  'mid' => 'audio/midi',
  'mp3' => 'audio/mpeg',
  'ogg' => 'application/ogg',
  'pdf' => 'application/pdf',
  'pps' => 'application/vnd.ms-powerpoint',
  'ppt' => 'application/vnd.ms-powerpoint',
  'ps' => 'application/postscript',
  'rtf' => 'application/rtf',
  'zip' => 'application/zip');

$file = $this->site->path.'/shop/'.$this->file;

if ($this->file != NULL) {
  if (file_exists($file)) {
    $tab = explode('/', $this->file);
    $filename = @$tab[count($tab)-1];
    $tab = explode('.', $filename);
    $ext = @$tab[count($tab)-1];
    if (isset($tabext[$ext])) {
      header ('Content-Type: '.$tabext[$ext]);
    } else {
      header ('Content-Type: application/octet-stream');
    }
    header ('Content-Length: '.filesize($file));
    header ('Content-Disposition: attachment; filename='.$filename);
    echo file_get_contents($file);
  } else {
    echo '<h2>Erreur</h2>';
    echo '<p>Fichier introuvable. Veuillez contacter le responsable de la boutique.</p>';
  }
}
?>