<h2>Téléchargement de votre commande</h2>
<?php if (count($this->music) == 0 && count($this->albummusic) == 0 && count($this->score) == 0 && count($this->albumscore) == 0): ?>
<p>Votre commande est vide.</p>
<?php else: ?>

<?php if (count($this->music) > 0 || count($this->albummusic)): ?>
<h3>Fichiers MP3 :</h3><p>
<?php
foreach ($this->albummusic as $album) {
  echo "<img src=\"".$this->path."/shop/albummusic.png\" alt=\"Fichiers MP3\" title=\"Fichiers MP3\" /> ";
	echo "Album : ".$album->title;
	$parts = explode('|', $album->musicfile);
	if (count($parts) > 1) {
		for ($i=0; $i<count($parts); $i++) {
			echo " <a href=\"".$this->url(array('module' => 'shop', 'controller' => 'download', 'action' => 'albummusic', 'orderid' => $this->order->id, 'key' => $this->order->key, 'id' => $album->id, 'part' => $i), 'format', true)."\">[Télécharger partie ".($i+1)."]</a><br />";
		}
	} else {
		echo " <a href=\"".$this->url(array('module' => 'shop', 'controller' => 'download', 'action' => 'albummusic', 'orderid' => $this->order->id, 'key' => $this->order->key, 'id' => $album->id), 'format', true)."\">[Télécharger]</a><br />";
	}
}
foreach ($this->music as $song) {
  echo "<img src=\"".$this->path."/shop/music.png\" alt=\"Fichier MP3\" title=\"Fichier MP3\" /> ";
	echo $song->title." <a href=\"".$this->url(array('module' => 'shop', 'controller' => 'download', 'action' => 'music', 'orderid' => $this->order->id, 'key' => $this->order->key, 'id' => $song->id), 'format', true)."\">[Télécharger]</a><br />";
}
?>
<?php endif; ?>

<?php if (count($this->score) > 0 || count($this->albumscore)): ?>
<h3>Partitions sélectionnées :</h3><p>
<?php
foreach ($this->albumscore as $album) {
  echo "<img src=\"".$this->path."/shop/albumscore.png\" alt=\"Partitions au format PDF\" title=\"Partitions au format PDF\" /> ";
	echo "Album : ".$album->title." <a href=\"".$this->url(array('module' => 'shop', 'controller' => 'download', 'action' => 'albumscore', 'orderid' => $this->order->id, 'key' => $this->order->key, 'id' => $album->id), 'format', true)."\">[Télécharger]</a><br />";
}
foreach ($this->score as $song) {
  echo "<img src=\"".$this->path."/shop/score.png\" alt=\"Partitions au format PDF\" title=\"Partitions au format PDF\" /> ";
	echo $song->title." <a href=\"".$this->url(array('module' => 'shop', 'controller' => 'download', 'action' => 'score', 'orderid' => $this->order->id, 'key' => $this->order->key, 'id' => $song->id), 'format', true)."\">[Télécharger]</a><br />";
}
?>
<?php endif; ?>

<?php endif; ?>