<?php
	$this->declareVars(array('can_download' => true));
?>
<p>
<?php echo (isset($this->tree->description))? $this->tree->description:''; ?>
</p>
<?php $this->headScript()->captureStart(); ?>
var lang_next = '<?=$this->_('Next'); ?>';
var lang_prev = '<?=$this->_('Prev'); ?>';
var lang_loading = '<?=$this->_('Loading...'); ?>';
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headStyle()->captureStart(); ?>
.download_hidden {
    display: none;
}

#photo_prev {
    float: left;
}

#photo_next {
    float: right;
}

#photo_titre {
    text-align: center;
    font-weight: bold;
}

#photo_image {
    clear: both;
    text-align: center;
}

#photo_loading {
    clear: both;
    text-align: center;
    color: white;
    background-color: green;
}
<?php $this->headStyle()->captureEnd(); ?>
<?php $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->path_common . '/mootools.v1.11.js'); ?>
<?php $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->path_common . '/gallery.js'); ?>
<a name="top"></a>
<div id="photo_titre"></div>
<div><span id="photo_prev"></span>
<span id="photo_next"></span>
</div>
<div id="photo_image"></div>
<div id="photo_loading"></div>

<br />
<?php
	if ($this->can_download):
?>
<form method="post" action="<?php echo $this->url(array('alias' => $this->tree->alias, 'format' => 'pzip'), 'format', true); ?>">
<div>
<input type="hidden" name="dir" value="<?php echo $this->photos_path ?>" />
<div id="download_link"><a href="#" onclick="display_download();"><?= $this->_('Download pictures'); ?></a></div>
<?php
	endif;
?>
<br />
<?php
	$i = 0;
	foreach ($this->photos as $photo):
?>
<a href="#top" onclick="display_picture(<?php echo $i++; ?>);">
<img src="<?php echo $photo['thumbnails']; ?>" width="<?php echo $photo['thumbnails_width']; ?>" height="<?php echo $photo['thumbnails_height']; ?>" title="<?php echo $photo['title']; ?>" alt="<?php echo $this->escape($photo['title']); ?>" class="no-border" />
</a>
<?php
	if ($this->can_download):
?>
<span class="download_hidden"><input type="checkbox" name="files[]" value="<?php echo $photo['file']; ?>" class="check"/></span>
<?php
	endif;
?>
<?php
	endforeach;
?>
<script type="text/javascript">
<?php
	$pict = '';
	foreach ($this->photos as $photo) {
		$pict .= '{"url":"'.$photo['url'] . '","title":"'.$photo['title'] . '"},';
	}
	echo 'var image = [', trim($pict, ','), '];';
?>
</script>
<?php
	if ($this->can_download):
?>
<div id="download_button" class="download_hidden">
<a href="#" onclick="select_all(); return false;"><?php echo $this->_('All'); ?></a>
<input type="submit" value="<?php echo $this->_('Download') ?>" /></div>
</div>
</form>
<?php
	endif;
?>