
<h1><img width="16" height="16" border="0"
	title="<?php
echo $this->_('Group')?>"
	alt="<?php
echo $this->_('Group')?>" class="folder" border="0"
	src="<?php
echo $this->path;
?>/images/icons/group.png" />&nbsp;<?php
echo $this->_('Group')?></h1>
<table cellpadding="0" cellspacing="0" width="100%" class="list">
	<thead>
		<tr>
			<th style="width: 16px">&nbsp;</th>
			<th style="width: 100px"><?php
echo $this->_('Name')?></th>
			<th style="width: 100px"><?php
echo $this->_('Parents')?></th>
			<th style="width: 40px" align="right"><?php
echo $this->_('Action')?></th>
		</tr>
	</thead>
	<?php
foreach ($this->groups_list as $group) :
    ?>
		<tr>
		<td>
			<?php
    echo $this->escape($group->id);
    ?>
			</td>
		<td>
			<?php
    echo $this->escape($group->name);
    ?>
			</td>
		<td>
			<?php
    echo $this->escape($group->parents);
    ?>
			</td>
		<td align="right"><a
			href="<?php
    echo $this->url(array('controller' => 'perm' , 'action' => 'edit' , 'format' => 'phtml' , 'id' => $group->id), 'format', true);
    ?>">
		<img width="16" height="16" border="0"
			title="<?php
    echo $this->_('Permission')?>"
			alt="<?php
    echo $this->_('Permission')?>" class="folder"
			src="<?php
    echo $this->path;
    ?>/images/icons/group_key.png" /> </a>
			<?php
    if ($group->type != 1) :
        ?>
				<a
			href="<?php
        echo $this->url(array('controller' => 'group' , 'action' => 'edit' , 'format' => 'phtml' , 'id' => $group->id), 'format', true);
        ?>">
		<img width="16" height="16" border="0"
			title="<?php
        echo $this->_('Edit')?>"
			alt="<?php
        echo $this->_('Edit')?>" class="folder"
			src="<?php
        echo $this->path;
        ?>/images/icons/group_edit.png" /> </a>
		<a
			href="<?php
        echo $this->url(array('controller' => 'group' , 'action' => 'delete' , 'format' => 'phtml' , 'id' => $group->id), 'format', true);
        ?>"
			onclick="return confirm('<?php
        echo $this->escape($this->_('Do you really want to delete this Group?'));
        ?>');">
		<img width="16" height="16" border="0"
			title="<?php
        echo $this->_('Delete')?>"
			alt="<?php
        echo $this->_('Delete')?>" class="folder"
			src="<?php
        echo $this->path;
        ?>/images/icons/group_delete.png" /> </a>

     else :
        ?>
				<img width="32" height="16" border="0" alt="" class="folder"
			src="<?php
        echo $this->path;
        ?>/images/px1.gif" />

    <?php
    endif;
    ?>
			</td>
	</tr>
	<?php
endforeach;
?>
	</table>
<br />
<a
	href="<?php
echo $this->url(array('controller' => 'group' , 'action' => 'add' , 'format' => 'phtml'), 'format', true);
?>">
<img width="16" height="16" border="0"
	title="<?php
echo $this->_('Add')?>"
	alt="<?php
echo $this->_('Add')?>" class="folder"
	src="<?php
echo $this->path;
?>/images/icons/group_add.png" />&nbsp;<?php
echo $this->_('Add');
?></a>
<hr />
<a
	href="<?php
echo $this->url(array('controller' => 'user'), 'format', true);
?>">
<img width="16" height="16" border="0"
	title="<?php
echo $this->_('Return')?>"
	alt="<?php
echo $this->_('Return')?>" class="folder"
	src="<?php
echo $this->path;
?>/images/icons/arrow_undo.png" />&nbsp;<?php
echo $this->_('Return');
?></a>