<table border="0" width="90%">
<tr><td class="t01"><?php echo $this->_('Date') ?> : </td><td><?= $this->message->date ?></td></tr>
<tr><td class="t01"><?php echo $this->_('Title') ?> : </td><td><?= $this->message->title ?></td></tr>
<?php if ($this->message->header): ?>
<tr><td class="t01"><?php echo $this->_('Header') ?> : </td><td><?= $this->message->header ?></td></tr>
<?php endif; ?>
<tr><td class="t01"><?php echo $this->_('Content') ?> : </td><td><?= $this->message->content ?></td></tr>
<tr><td colspan="2" align="center"><a href="<?= $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'edit', 'message_id' => $this->message->id), 'format'); ?>"><?php echo $this->_('Edit') ?></a></td></tr>
</table>

	<table cellpadding="0" cellspacing="0" class="list">
	<thead>
		<tr>
			<th style="width:32px">&nbsp;</th>
			<th style="width:50px"><?php echo $this->_('Username') ?></th>
			<th style="width:400px"><?php echo $this->_('Content') ?></th>
			<th style="width:50px"><?php echo $this->_('Date') ?></th>
			<th style="width:40px" align="right"><?php echo $this->_('Action') ?></th>
		</tr>
	</thead>
	<?php
		foreach ($this->comments_list as $comment): ?>
		<tr>
			<td>
			<?php echo $this->escape($comment->id); ?></td>
			<td>
			<?php echo $this->escape($comment->username); ?>
			</td>
			<td>
			<?php echo $this->escape($comment->content); ?>
			</td>
			<td>
			<?php echo $this->escape($comment->date); ?>
			</td>
			<td align="right">
				<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'edit', 'format' => 'phtml', 'blogcomment_id' => $comment->id), 'format', true); ?>">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Edit') ?>" alt="<?php echo $this->_('Edit') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/pencil.png"/>
				</a>
				<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'delete', 'format' => 'phtml', 'blogcomment_id' => $comment->id), 'format', true); ?>"  onclick="return confirm('<?php echo $this->escape($this->_('Do you really want to delete this comment ?')); ?>');">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Delete') ?>" alt="<?php echo $this->_('Delete') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/cross.png"/>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
	<?php
echo $this->comments_list; //Print the pagination control
   ?>
<br />
<hr />
<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tree', 'action' => 'edit', 'id' => $this->message->tree_parentid), 'format'); ?>"><?php echo $this->_('Return'); ?></a>