<?php
        $message = $this->message;
        $comments = $message->findBlogComment();
        $form = $this->form;
        $form->populate(array('blogmessage_id' => $message->id))
     ?>
<a name="<?php echo $message->title ?>"></a>
<h3><?php echo $message->title ?></h3>

<?php if (!empty($message->header)): ?>
<p><?php echo $message->header; ?></p>
<?php endif; ?>
<p><?php echo $message->content; ?></p>
         <p class="post-footer align-right">
                    <?php
          	    if ($this->module->config->display_author && !empty($message->user_id)) {
          	        $users = $user_table->find($message->user_id);
          	        if (count($users)) {
          	            $user = $users->current();
          	            echo $this->_('By %s', $user->firstname . ' ' . $user->lastname);
          	        }
          	    }
                    ?>
                <?php if (!empty($message->header)): ?>
                	<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $this->tree->alias, 'mid' => $message->id), 'format') ?>" class="readmore"><?php echo $this->_('Read more...'); ?></a>
                <?php endif; ?>
          	    <?php if (!empty($message->tree_id)):
                    $treetable = new Jimw_Site_Tree();
                    $messagetree = $treetable->find($message->tree_id)->current();
          	    ?>
          	    <a href="<?php echo $this->url(array('format' => 'phtml', 'alias' => $messagetree->alias), 'alias') ?>" class="readmore"><?php echo $this->_('See more (%s)...', $messagetree->menutitle); ?></a>
          	    <?php endif; ?>
		<?php if ($this->tree->param->comment && $message->comment): ?>
          <?php if (count($comments) > 0): ?>
            <a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $this->tree->alias, 'mid' => $message->id), 'format'); ?>" onclick="javascript:el = document.getElementById('comments<?php echo $message->id ?>'); el.style.display=(el.style.display=='none') ? 'block':'none'; return false;" class="comments"><?php echo $this->_('%d Comments', $comments->getTotalItemCount()); ?></a>
          <?php  else: ?>
            <a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'add', 'format' => 'phtml', 'alias' => $this->tree->alias, 'blogmessage_id' => $message->id), 'format'); ?>" onclick="javascript:el = document.getElementById('addcomment<?php echo $message->id ?>'); el.style.display=(el.style.display=='none') ? 'block':'none'; return false;" class="comments"><?php echo $this->_('Add comment'); ?></a>
          <?php endif; ?>
        <?php endif; ?>
            <?php if ($this->module->config->display_date): ?>
            <span class="date"><?php echo $this->date($message->date, Zend_Date::DATE_MEDIUM); ?></span>
            <?php endif; ?>
         </p>
        <?php if ($this->tree->param->comment && $message->comment): ?>
         <?php if (count($comments) > 0): ?>
         	<div class="post-footer" id="comments<?php echo $message->id; ?>" style="display: none">
        	<?php foreach($comments as $comment): ?>
          	  <p>
          	  	<small><b><?php echo $this->_('By %1$s the %2$s', $comment->username, $this->date($comment->date)); ?></b><br />
          	      <?php echo nl2br($comment->content); ?>
          	    </small>
          	  </p>
            <?php endforeach; ?>
            <?php if ($comments->getCurrentItemCount() < $comments->getTotalItemCount()): ?>
			<div id="labelnextcomment<?php echo $message->id ?>">
            	<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $this->tree->alias, 'mid' => $message->id), 'format') ?>"><?php echo $this->_('Next comments'); ?> &nbsp;&gt;&gt;</a>
            </div>
            <?php endif; ?>
            <div id="labeladdcomment<?php echo $message->id ?>">
            	<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'add', 'format' => 'phtml', 'alias' => $this->tree->alias, 'blogmessage_id' => $message->id), 'format'); ?>" onclick="javascript:el = document.getElementById('addcomment<?php echo $message->id ?>'); el.style.display=(el.style.display=='none') ? 'block':'none'; return false;" class="comments"><?php echo $this->_('Add comment'); ?></a>
            </div>
           	<div id="addcomment<?php echo $message->id ?>" style="display: none;">
                <?php echo $form; ?>
        	</div>
        </div>
        <?php else: ?>
        	<div id="addcomment<?php echo $message->id ?>" style="display: none;">
                <?php echo $form; ?>
        	</div>
        <?php endif; ?>
       <?php endif; ?>