<h1><img width="16" height="16" border="0"
	title="<?php
echo $this->_('Permission')?>"
	alt="<?php
echo $this->_('Permission')?>" class="folder" border="0"
	src="<?php
echo $this->path;
?>/images/icons/key.png" />&nbsp;<?php
echo $this->_('Permission')?></h1>
<?php echo $this->form; ?>
<br style="clear: both;" />
<p class="t01" style="font-size: 12px;">
<a href="<?php
echo $this->url(array('controller' => 'group' , 'action' => 'list' , 'format' => 'phtml'), 'format', true);
?>" class="jimw-return">
    <?php echo $this->_('Return'); ?>
</a>
</p>