<?= (!empty($this->tree->description)) ? '<p>' . $this->tree->description . '</p>' : ''; ?>

<? if (!empty($this->article)): ?>
<div id="article-toolbar" style="float: right;">
<a href="<?php echo $this->url(array('alias' => $this->tree->alias, 'format' => 'pdf'), 'alias', false); ?>"><img src="<?php echo JIMW_URL_PUBLIC_COMMON_PATH ?>/pdf.png" id="article-pdf" alt="" title="<?php echo $this->_('View this page in PDF'); ?>" align="middle" border="0" /></a>
<a href="<?php echo $this->url(array('alias' => $this->tree->alias, 'format' => 'print'), 'alias', false); ?>"><img src="<?php echo JIMW_URL_PUBLIC_COMMON_PATH ?>/print.png" id="article-print" alt="" title="<?php echo $this->_('Print this page'); ?>" align="middle" border="0" /></a>
</div>
<?php echo $this->protectMail($this->bbCode($this->aliasLink($this->article->content))); ?>
<? else: ?>
<p><?php echo $this->_('Article not found'); ?></p>
<? endif; ?>