<?php if (isset($this->files['Files'])): ?>
	<img width="16" height="18" class="folder" src="<?php echo $this->path; ?>/javascripts/extjs/resources/images/default/tree/folder-open.gif"/> 
	<?php 
		echo '<a href="', $this->request->getBaseUrl (),'/file/list/ext/phtml?path=/">root</a>&nbsp;/&nbsp;';
		$p = '';
		$path = explode('/', $this->file_path);
		for ($i = 1; $i < count($path); $i++) {
			if ($path[$i] != '') {
				$p .= '/' . $path[$i];
				echo '<a href="', $this->request->getBaseUrl (),'/file/list/ext/phtml?path=', $p, '">', $path[$i], '</a>&nbsp;/&nbsp;';
			}
		}
	?>
	<table>
	<thead>
		<tr>
			<th style="width:16px">&nbsp;</th>
			<th style="width:80%">Name</th>
			<th style="width:40px">Size</th>
			<th style="width:300px">Action</th>
		</tr>
	</thead>
	<?php if (isset($this->file_path_up)): ?>
	<tr>
		<td><img width="16" height="18" class="folder" src="<?php echo $this->path; ?>/javascripts/extjs/resources/images/default/tree/folder.gif"/></td>
		<td colspan="3">
			<a href="<?php echo $this->request->getBaseUrl (); ?>/file/list/ext/phtml?path=<?php echo $this->file_path_up; ?>">&nbsp;..&nbsp;</a>
		</td>
	</tr>
	<?php endif; 
		foreach ($this->files['Files'] as $file): ?>
		<tr>
			<td><img width="16" height="18" class="folder" src="<?php echo $this->path . ($file['cls'] == 'folder' ? '/javascripts/extjs/resources/images/default/tree/folder.gif' : '/javascripts/extjs/resources/images/default/tree/leaf.gif') ?>"/></td>
			<td>
			<?php if ($file['cls'] == 'folder') { ?>
				<a href="<?php echo $this->request->getBaseUrl (); ?>/file/list/ext/phtml?path=<?php echo $file['path']; ?>"><?php echo $file['name'] ?></a>
			<?php } else { echo $file['name']; }?>
			</td>
			<td><?php echo $file['size']; ?></td>
			<td>
				<a href="#" onclick="if (confirm('Do you realy want to delete this file ?')) window.location = '<?php echo $this->request->getBaseUrl (); ?>/file/delete/ext/phtml?file=<?php echo $file['path'] ?>'">
					<img width="16" height="18" border="0" class="folder" src="<?php echo $this->path; ?>/images/icons/cross.png"/>
				</a>
				<a href="#" onclick="var name = prompt('Rename to ?', '<?php echo $file['name']; ?>'); if (name != null && name != '<?php echo $file['name']; ?>') window.location = '<?php echo $this->request->getBaseUrl (); ?>/file/rename/ext/phtml?oldname=<?php echo $file['path'] ?>&newname=<?php echo $this->file_path; ?>/' + name;">
					<img width="16" height="18" border="0" class="folder" src="<?php echo $this->path; ?>/images/icons/pencil.png"/>
				</a>
				<a href="<?php echo $this->request->getBaseUrl (); ?>/file/rename/ext/phtml?path=<?php echo $file['path'] ?>">
					<img width="16" height="18" border="0" class="folder" src="<?php echo $this->path; ?>/images/icons/arrow_down.png"/>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
	<hr />
	<form action="<?php echo $this->request->getBaseUrl (); ?>/file/newdir/ext/phtml">
	New Directory: <input type="text" name="dir" value="<?php echo $this->file_path; ?>/">
	<input type="submit" value="Submit" />
	</form>
	<hr />
	<form action="<?php echo $this->request->getBaseUrl (); ?>/file/upload/ext/phtml">
	<input type="hidden" name="path" value="<?php echo $this->file_path; ?>/">
	Upload File: <input type="file" name="file" value="<?php echo $this->file_path; ?>/" />
	<input type="submit" value="Submit" />
	</form>
<?php else:
	if (!$this->files['success']) { echo '<font color="red">', $this->files['error'], '</font>'; } ?>
	<br /><a href="<?php echo $this->request->getBaseUrl (); ?>/file/list/ext/phtml?path=<?php echo $this->file_path; ?>">Return</a>
	<br />
	
<?php endif;?>