<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<!-- Load Queue widget CSS and jQuery -->
<style type="text/css">@import url(<?php echo $this->path?>/plupload/css/plupload.queue.css);</style>
<link href="/admin/public/stylesheets/start/jquery-ui-1.8.4.css" rel="stylesheet" type="text/css" /> 
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
	google.load("jquery", "1.3");
</script>

<!-- Thirdparty intialization scripts, needed for the Google Gears and BrowserPlus runtimes -->
<script type="text/javascript" src="<?php echo $this->path?>/plupload/js/gears_init.js"></script>
<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>

<!-- Load plupload and all it's runtimes and finally the jQuery queue widget -->
<script type="text/javascript" src="<?php echo $this->path?>/plupload/js/plupload.full.min.js"></script>
<script type="text/javascript" src="<?php echo $this->path?>/plupload/js/jquery.plupload.queue.min.js"></script>

<script type="text/javascript">
// Convert divs to queue widgets when the DOM is ready
$(function() {
	$("#uploader").pluploadQueue({
		// General settings
		runtimes : 'html5,gears,browserplus,flash,silverlight,browserplus,html4',
		url : '<?php echo $this->url(array('module'=>'default' ,'action' => 'plupload','controller'=>'file', 'dir'=>$this->dir), 'get', true); ?>',
		max_file_size : '10mb',
		chunk_size : '1mb',

		// Specify what files to browse for
		filters : [
			{title : "Image files", extensions : "jpg,gif,png"},
			{title : "Archives files", extensions : "zip,rar,7zip,tar,tgz,tar.gz,tar.bzip2"},
			{title : "Documents files", extensions : "doc,docx,pdf,xls,xlsx,ppt,pptx,odt,odp"},
			{title : "Web files", extensions : "html,css,js"}
		],

		// Flash settings
		flash_swf_url : '<?php echo $this->path?>/plupload/js/plupload.flash.swf',

		// Silverlight settings
		silverlight_xap_url : '<?php echo $this->path?>/plupload/js/plupload.silverlight.xap'
	});

	// Client side form validation
	$('form').submit(function(e) {
		var uploader = $('#uploader').pluploadQueue();

		// Validate number of uploaded files
		if (uploader.total.uploaded == 0) {
			// Files in queue upload them first
			if (uploader.files.length > 0) {
				// When all files are uploaded submit form
				uploader.bind('UploadProgress', function() {
					if (uploader.total.uploaded == uploader.files.length)
						$('form').submit();
				});
                                uploader.bind('FileUploaded',function(upr, file, data){
                                        if(upr.total.queued == 0) {
                                            window.close();
                                        }
                                });

				uploader.start();
			} else
				alert('You must at least upload one file.');

			e.preventDefault();
		}
	});
});
</script>
<form action="">
	<div id="uploader">
		<p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
	</div>
</form>
			