<?php
	if ($this->request->isXmlHttpRequest()):
		echo $this->getContent();
		return;
	else:

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>


<head>
<title><?php echo $this->request->getDomainName (); ?> - <?= $this->tree['tree_menutitle']; ?></title>
<link rel="stylesheet" type="text/css" href="<?= $this->path ?>/jesusway.css">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="Content-Language" content="fr">
<script src="<?= $this->path ?>/mootools.v1.11.js"></script>
<script>
<!--
function load_page(url) {
	//var content = new Fx.Slide('slide', {duration : 500});
	//content.slideOut(); //toggle the slider up and down.
	new Ajax(url, {method: 'get', update: 'content', onComplete: function() {
		//content.slideIn ();
	}}).request();
	return false;
}
-->
</script>
</head>


<body>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
	<td class="bg"><img src="<?= $this->path ?>/images/px1.gif" width="1" height="1" alt="" border="0"></td>
	<td class="bgleft"><img src="<?= $this->path ?>/images/bg_left.gif" alt="" width="17" height="16" border="0"></td>
	<td>

<table border="0" cellpadding="0" cellspacing="0" width="780" class="fontop">
<tr>
	<td>
<table border="0" cellpadding="0" cellspacing="0" width="780">
<tr>
	<td align="center" width="150"><img src="<?= $this->path ?>/images/logo.png" alt="Logo Jimw.fr" border="0"></td><td class="title"><?= $this->tree['tree_pagetitle']; ?></td>

	<td align="center" class="citation"></td>

	<td align="right">




<p><a href="http://validator.w3.org/check/referer"><img src="<?= $this->path ?>/images/valid_html4.gif" alt="Valid HTML 4.0 Transitional" height="15" width="80" border="0"></a><br><font style="font-size: 4px;">&nbsp;</font><br><a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="<?= $this->path ?>/images/valid_css.png" alt="Valid CSS" height="15" width="80" border="0"></a><br><font style="font-size: 4px;">&nbsp;</font><br><img src="<?= $this->path ?>/images/php.png" alt="PHP" height="15" width="80" border="0"><br><font style="font-size: 4px;">&nbsp;</font><br><img src="<?= $this->path ?>/images/mysql.gif" alt="MySQL" height="15" width="80" border="0"></p>



</td></tr>
</table>
	</td>
</tr>
</table>

<table border="0" cellpadding="0" cellspacing="0" width="780" class="fontop01">
<tr>
	<td>
<table border="0" cellpadding="0" cellspacing="0">
<tr>
<?php
foreach ($this->menu('top') as $menuitem) {
?>
<td>
	<p class="menu01">
		<a href="<?= $menuitem->toUrl () ?>"><img src="<?= $this->path ?>/images/b_go.gif" width="19" height="25" alt="" border="0" class="absmiddle">&nbsp;&nbsp;<?php echo $menuitem->menutitle; ?></a>
	</p>
</td>
<?php } ?>
</tr>
</table>
	</td>
</tr>
</table>






<table border="0" cellpadding="0" cellspacing="0" width="780">
<tr bgcolor="#AFC0D0" valign="top">
	<td width="487">
	<div id="slide">
	<div id="content">
	<?php echo $this->getContent(); ?>
	</div>
	</div>
	</td>
	<td width="2" class="dotsw"><img src="<?= $this->path ?>/images/px1.gif" alt="" width="1" height="1" border="0"></td>
</tr>
</table>



<table border="0" cellpadding="0" cellspacing="0" width="780">
<tr>
	<td colspan="2"><img src="<?= $this->path ?>/images/px1.gif" width="1" height="1" alt="" border="0"></td>
</tr>
<tr bgcolor="#28549E">
	<td height="19" colspan="2"><img src="<?= $this->path ?>/images/px1.gif" width="1" height="1" alt="" border="0"></td>
</tr>
<tr>
	<td height="70"><p>Copyright &copy; 2006 - 2007 <?php echo $this->request->getDomainName (); ?> /
<a href="http://www.logisim.com" target="_blank">Simon LEPRINCE</a> /
<a href="http://www.lesgrumels.fr" target="_blank">lesgrumels</a></p></td>
	<td></td>
</tr>
</table>
	</td>
	<td class="bgright"><img src="<?= $this->path ?>/images/bg_right.gif" alt="" width="17" height="16" border="0"></td>
	<td class="bg"><img src="<?= $this->path ?>/images/px1.gif" width="1" height="1" alt="" border="0"></td>
</tr>
</table>
	</body>
</html>
<?php
	endif;