<h2>Téléchargement de votre commande</h2>
<form method="post" action="<?php echo $this->url(array('module' => 'shop', 'controller' => 'websalto', 'action' => 'download', 'basketid' => $this->basketid), 'format', true); ?>">
<p>Merci d'indiquer le nom de famille précisé lors de la commande : 
<input type="text" name="name" maxlength="30" />
</p>
<input type="submit" value="Valider" />
</form>
