<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>


<head>
<title><?php echo $this->request->getDomainName (); ?> - Administration</title>
<link rel="stylesheet" type="text/css" href="<?= $this->path ?>/jesusway.css">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="Content-Language" content="fr">

</head>


<body>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
	<td class="bg"><img src="<?= $this->path ?>/images/px1.gif" width="1" height="1" alt="" border="0"></td>
	<td class="bgleft"><img src="<?= $this->path ?>/images/bg_left.gif" alt="" width="17" height="16" border="0"></td>
	<td>

<table border="0" cellpadding="0" cellspacing="0" width="780" class="fontop">
<tr>
	<td>
<table border="0" cellpadding="0" cellspacing="0" width="780">
<tr>
	<td align="center" width="150"><img src="<?= $this->path ?>/images/logo.png" alt="Logo Jimw.fr" border="0"></td><td class="title"><?php echo $this->request->getDomainName (); ?> - Administration</td>

	<td align="center" class="citation"></td>

	<td align="right">




<p><a href="http://validator.w3.org/check/referer"><img src="<?= $this->path ?>/images/valid_html4.gif" alt="Valid HTML 4.0 Transitional" height="15" width="80" border="0"></a><br><font style="font-size: 4px;">&nbsp;</font><br><a href="http://jigsaw.w3.org/css-validator/check/referer"><img src="<?= $this->path ?>/images/valid_css.png" alt="Valid CSS" height="15" width="80" border="0"></a><br><font style="font-size: 4px;">&nbsp;</font><br><img src="<?= $this->path ?>/images/php.png" alt="PHP" height="15" width="80" border="0"><br><font style="font-size: 4px;">&nbsp;</font><br><img src="<?= $this->path ?>/images/mysql.gif" alt="MySQL" height="15" width="80" border="0"></p>



</td></tr>
</table>
	</td>
</tr>
</table>

<table border="0" cellpadding="0" cellspacing="0" width="780" class="fontop01">
<tr>
	<td>
<table border="0" cellpadding="0" cellspacing="0">
<tr>
<td>
	<p class="menu01">
		<a href="<?= $this->request->getBaseUrl() ?>"><img src="<?= $this->path ?>/images/b_go.gif" width="19" height="25" alt="" border="0" class="absmiddle">&nbsp;&nbsp;Pages</a>
	</p>
</td>
<td>
	<p class="menu01">
		<a href="<?= $this->request->getBaseUrl() ?>"><img src="<?= $this->path ?>/images/b_go.gif" width="19" height="25" alt="" border="0" class="absmiddle">&nbsp;&nbsp;Sites</a>
	</p>
</td>
<td>
	<p class="menu01">
		<a href="<?= $this->request->getBaseUrl() ?>"><img src="<?= $this->path ?>/images/b_go.gif" width="19" height="25" alt="" border="0" class="absmiddle">&nbsp;&nbsp;Configuration</a>
	</p>
</td>
</tr>
</table>
	</td>
</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="780">
<tr bgcolor="#AFC0D0" valign="top">
	<td width="487">