<p>This url was visited <?php echo $this->visited ?> times</p>
<form action="<?php echo $this->url(array('module' => 'links', 'controller' => 'manage', 'action' => 'save', 'ext' => 'phtml', 'id' => $this->id), 'ext', true); ?>" method="post">
<input type="hidden" name="id" value="<?= $this->id ?>">
<table border="0" width="90%">
<tr><td class="t01"><?php echo $this->_('Redirect URL') ?> : </td><td><input type="text" name="redirect_url" value="<?= $this->redirect_url ?>"></td></tr>
<tr><td colspan="2" align="center"><input type="submit" name="btn" value="<?php echo $this->_('Save') ?>"></td></tr>
</table></form>
<br/>
<p class="t01" style="font-size: 12px;">
	<a href="<?= $this->request->getBaseUrl() ?>"><?php echo $this->_('Return') ?></a>
</p>