<script type="text/javascript">
function showLyrics(text) {
  var b = document.createElement('div');
  b.id = 'lyrics';
  b.setAttribute('style', 'position: absolute; text-align: left; overflow: auto; left: 50%; top: 50%; width: 400px; height: 350px; margin-left: -200px; margin-top: 0px; border: black 1px solid; background-color: white; color: black; z-index: 200');
  var c = document.createElement('p');
  c.innerHTML = '<a href="#" onclick="javascript:document.body.removeChild(document.getElementById(\'lyrics\'));"><img src="<?php echo $this->path; ?>/shop/close.png" alt="X" title="Fermer" border="0" /></a>';
  c.setAttribute('style', 'float: right; display; inline;');
  b.appendChild(c);
  var l = document.createElement('p');
  l.innerHTML = text;
  l.setAttribute('style', 'float: left; margin: 3px;');
  b.appendChild(l);
  document.body.appendChild(b);
}
</script>

<form method="post" action="<?php echo $this->url(array('module' => 'shop', 'controller' => 'basket', 'action' => 'add'), 'format', true); ?>">
<?php

function formatprice($price) {
  return (substr($price, -3) == '.00' ? substr($price, 0, -3) : $price);
}

$rep = trim($this->tree->getParam('dir'), '/');
$dir = rtrim('/' . $this->tree->site->path, '/') . '/' . $rep . 'shop/';

foreach ($this->albums as $album) {
  
  // Album
  
  echo "<table border=\"0\" width=\"100%\"><tr>";
  echo "<td><h2>".$album->title."</h2>\n";
  echo "<h4>Artiste : ".$album->artist."<br />".
       "Editeur : ".$album->editor."<br />".
       "Année : ".$album->year."</h4>";
  echo "<br />".$this->tree->description."</td><td>";
  
  if ($album->musicprice > 0) {
    echo "<img src=\"".$this->path."/shop/albummusic.png\" alt=\"Fichiers MP3\" title=\"Fichiers MP3\" /> ";
    $disabled = (isset($this->basket->albummusic[$album->id])) ? " disabled=\"disabled\"" : "";
    echo "<input type=\"checkbox\" name=\"checkalbummusic[".$album->id."]\" value=\"1\" $disabled/> Acheter l'album complet (".formatprice($album->musicprice)." &euro;)<br />";
  }
  if ($album->scoreprice > 0) {
    echo "<img src=\"".$this->path."/shop/albumscore.png\" alt=\"Partitions au format PDF\" title=\"Partitions au format PDF\" /> ";
    $disabled = (isset($this->basket->albumscore[$album->id])) ? " disabled=\"disabled\"" : "";
    echo "<input type=\"checkbox\" name=\"checkalbumscore[".$album->id."]\" value=\"1\" $disabled/> Acheter toutes les partitions (".formatprice($album->scoreprice)." &euro;)<br />";
  }


  if ($album->image != '') echo "<td align=\"right\"><img src=\"".$dir.$album->image."\" alt=\"&nbsp;\" /></td>";
  
  echo "</tr></table>";
  
  // Songs
  $songmodel = new ShopSong();
  $songs = $songmodel->findByAlbum($album->id);
  $show = array('music' => false,
	              'score' => false,
								'lyrics' => false,
								'musicpreview' => false);
  foreach ($songs as $song) {
    if ($song->musicprice > 0) $show['music'] = true;
    if ($song->scoreprice > 0) $show['score'] = true;
    if ($song->lyrics != '') $show['lyrics'] = true;
    if ($song->musicpreview != '') $show['musicpreview'] = true;
  }
  ?>
  <table border="0" width="100%">
	<tr>
	  <th>Titre</th><?php
		if ($show['music']) echo '<th>MP3</th>';
		if ($show['score']) echo '<th>Partition</th>';
		if ($show['lyrics']) echo '<th>Paroles</th>';
		if ($show['musicpreview']) echo '<th>Ecoute</th>';
		?></tr>
	<?php
  
  foreach ($songs as $song) {
    // Song title
    echo "<tr><td style=\"line-height: 100%;\">".$song->title;
    //if ($song->artist != '') echo " (".$song->artist.")";
    if ($song->artist != '' || $song->editor != '') {
      echo '<br /><span style="font-size: 0.8em; color: #BBB;">&nbsp; &nbsp; '.trim($song->artist.($song->editor == '' ? '' : ' &copy; '.$song->editor)).'</span>';
    }
    // Music checkbox
    if ($show['music']) {
      echo "</td><td>";
      if ($song->musicprice > 0) {
        $disabled = (isset($this->basket->music[$song->id]) || isset($this->basket->albummusic[$song->shopalbum_id])) ? " disabled=\"disabled\"" : "";
        echo "<img src=\"".$this->path."/shop/music.png\" alt=\"Fichier MP3\" title=\"Fichier MP3\" /> ";
        echo "<input type=\"checkbox\" name=\"checkmusic[".$song->id."]\" value=\"1\" $disabled/> ";
        echo formatprice($song->musicprice)." &euro;";
      } else echo '&nbsp;';
    }
    // Score checkbox
    if ($show['score']) {
      echo "</td><td>";
      if ($song->scoreprice > 0) {
        $disabled = (isset($this->basket->score[$song->id]) || isset($this->basket->albumscore[$song->shopalbum_id])) ? " disabled=\"disabled\"" : "";
        echo "<img src=\"".$this->path."/shop/score.png\" alt=\"Partitions au format PDF\" title=\"Partitions au format PDF\" /> ";
        echo "<input type=\"checkbox\" name=\"checkscore[".$song->id."]\" value=\"1\" $disabled/> ";
        echo formatprice($song->scoreprice)." &euro;";
      } else echo '&nbsp;';
		}
    // Lyrics
    if ($show['lyrics']) {
      echo "</td><td>";
      if ($song->lyrics != '') {
        echo "<img src=\"".$this->path."/shop/lyrics.png\" alt=\"Afficher les paroles\" title=\"Afficher les paroles\" onclick=\"javascript:showLyrics('".str_replace("'", "\\'", str_replace("\n", "<br />", str_replace("\r", "", $this->bbCode($song->lyrics))))."');\" />";
      } else echo '&nbsp;';
		}
		// Preview
		if ($show['musicpreview']) {
      echo "</td><td>";
      if ($song->musicpreview != '') echo $this->bbCode("[mp3]shop/".$song->musicpreview."[/mp3]"); else echo '&nbsp;';
		}
    echo "</td></tr>";  
  
  }
  
  echo "</table>";
}

?>
<input type="submit" value="Ajouter au panier" />
</form>