<h2>Contenu de votre panier</h2>
<?php if (count($this->score) == 0 && count($this->albumscore) == 0 && 
          count($this->music) == 0 && count($this->albummusic) == 0): ?>
<p>Votre panier est vide.</p>
<?php else: ?>
<?php $sum = 0; ?>
<form method="post" action="<?php echo $this->url(array('module' => 'shop', 'controller' => 'basket', 'action' => 'confirm'), 'format', true); ?>">
<?php include_once('list.phtml'); ?>
<p>Total : <b><?php echo $sum ?> &euro;</b></p>

<p>Nom : <input type="text" name="name" /></p>
<p>Prénom : <input type="text" name="firstname" /></p>
<p>Email : <input type="text" name="email" /><small> (pour recevoir les partitions)</small></p>
<input type="submit" value="Confirmer et payer en ligne" />
</form>
<?php endif; ?>