<h2>Contenu de votre commande</h2>
<?php if (is_null($this->songs)): ?>
<p>Votre commande est vide.</p>
<?php else: ?>
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
<p>Partitions sélectionnées :</p>
<ul>
<?php
$sum = 0;
foreach ($this->songs as $song) {
	$sum += $song->scoreprice;
	echo "<li>".$song->title."</li>";
}
?>
</ul>
<p>Total : <b><?php echo $sum ?> &euro;</b></p>

<p>Nom : <?php echo $this->item->name; ?></p>
<p>Prénom : <?php echo $this->item->firstname; ?></p>
<p>Email : <?php echo $this->item->email; ?></p>

<p><b>Merci de conserver la référence de la transaction : <?php echo $this->orderid; ?></b></p>

<p>Cliquez sur le bouton <b>Payer</b> ci-dessous pour procéder au paiement. Ensuite, sur la page qui va s'afficher, cliquez sur le lien <b>Continuer</b> en bas à gauche, qui se trouve en dessous de <b>Vous n'avez pas de compte PayPal ?</b></p>

<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="clients@logisim.fr">
<input type="hidden" name="lc" value="FR">
<input type="hidden" name="item_name" value="Partitions sur le site du MEJ">
<input type="hidden" name="item_number" value="<?php echo $this->orderid; ?>">
<input type="hidden" name="amount" value="<?php echo $sum; ?>">
<input type="hidden" name="currency_code" value="EUR">
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="rm" value="1">
<input type="hidden" name="return" value="http://www.mej.fr">
<input type="hidden" name="cancel_return" value="http://www.mej.fr">
<input type="hidden" name="bn" value="PP-BuyNowBF:btn_paynowCC_LG.gif:NonHosted">
<input type="image" src="https://www.paypal.com/fr_FR/FR/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="">
<img alt="" border="0" src="https://www.paypal.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
</form>

<?php endif; ?>