<?php
$this->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href'=> $this->path . '/stylesheets/indigo.css'));
$this->headTitle()->prepend($this->request->getDomainName (). ' - Administration');
if (JIMW_UTF8) $this->headMeta('text/html; charset=UTF8', 'content-type');
if (isset($this->tree->menutitle))
    $this->headTitle()->append(' - ' . $this->tree->menutitle);
echo $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT);
?>
<html>
<head>
<?= $this->headTitle(); ?>
<?= $this->headMeta(); ?>
<?= $this->headLink(); ?>
<?= $this->headStyle(); ?>
<?= $this->headScript(); ?>
</head>

<body>
	<div class="toolbar">
		<div class="toolbar_left"><a href="<?= $this->url(array('controller' => 'index', 'action' => 'index', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Intro'); ?></a></div>
		<div class="toolbar_right">
		<?php
		$auth = Zend_Auth::getInstance();
		$user = $auth->getStorage()->read();
		echo $this->_('Hello'), ' ', $user->user_firstname, ' ', $user->user_lastname;
		 ?>&nbsp;<a href="<?= $this->url(array('controller' => 'auth', 'action' => 'logout', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Logout'); ?></a></div>
	</div>
<div class="container">

	<div class="header">
		
		<div class="title">
			<h1><?php echo $this->request->getDomainName (); ?> - Administration</h1>
		</div>

		<div class="navigation">
			<a href="<?= $this->url(array('controller' => 'index', 'action' => 'index', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Intro'); ?></a>
			<a href="<?= $this->url(array('controller' => 'tree', 'action' => 'list', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Pages'); ?></a>
			<a href="<?= $this->url(array('controller' => 'file', 'action' => 'index', 'ext' => 'ajax'), 'ext', true) ?>"><?= $this->_('Files'); ?></a>
			<a href="<?= $this->url(array('controller' => 'user', 'action' => 'index', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Users'); ?></a>
			<a href="<?= $this->url(array('controller' => 'system', 'action' => 'index', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('System'); ?></a>
			<div class="clearer"><span></span></div>
		</div>

	</div>

	<div class="main">
		
<div class="content">
			<?php echo $this->layout()->content; ?>
</div>

<?php
	switch ($this->request->getControllerName()){
		case 'system':
		case 'module':
		case 'domain':
		case 'site':
		case 'database':
			echo $this->render('system/menu.phtml'); 
			break;
		case 'user':
		case 'group':
		case 'perm':
			echo $this->render('user/menu.phtml'); 
			break;	}
?>
	
		<div class="clearer"><span></span></div>

	</div>

</div>

<div class="footer">&copy; 2006-2008 <a href="http://www.jimw.fr">JIMW</a> / 
<a href="http://www.logisim.fr" target="_blank">Simon LEPRINCE</a> / 
<a href="http://www.lesgrumels.fr" target="_blank">lesgrumels</a>. Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a href="http://validator.w3.org/check?uri=referer">XHTML</a>. Template design by <a href="http://arcsin.se">Arcsin</a>. <a href="<?php echo $this->request->getBaseUrl() ?>/">AJAX version</a>
</div>

</body>

</html>