<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
<meta name="description" content="description"/>
<meta name="keywords" content="keywords"/> 
<meta name="author" content="author"/> 
<link rel="stylesheet" type="text/css" href="<?= $this->path ?>/stylesheets/indigo.css" media="screen"/>
<title><?php echo $this->request->getDomainName (); ?> - Administration</title>
</head>

<body>

<div class="container">

	<div class="header">
		
		<div class="title">
			<h1><?php echo $this->request->getDomainName (); ?> - Administration</h1>
		</div>

		<div class="navigation">
			<a href="<?= $this->url(array('controller' => 'index', 'action' => 'index', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Intro'); ?></a>
			<a href="<?= $this->url(array('controller' => 'tree', 'action' => 'list', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Pages'); ?></a>
			<a href="<?= $this->url(array('controller' => 'file', 'action' => 'list', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('Files'); ?></a>
			<a href="<?= $this->url(array('controller' => 'system', 'action' => 'index', 'ext' => 'phtml'), 'ext', true) ?>"><?= $this->_('System'); ?></a>
			<div class="clearer"><span></span></div>
		</div>

	</div>

	<div class="main">
		


			<?php echo $this->getContent(); ?>


	
		<div class="clearer"><span></span></div>

	</div>

</div>

<div class="footer">&copy; 2006-2007 <a href="http://www.jimw.fr">JIMW</a> / 
<a href="http://www.logisim.com" target="_blank">Simon LEPRINCE</a> / 
<a href="http://www.lesgrumels.fr" target="_blank">lesgrumels</a>. Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a href="http://validator.w3.org/check?uri=referer">XHTML</a>. Template design by <a href="http://arcsin.se">Arcsin</a>. <a href="<?php echo $this->request->getBaseUrl() ?>/">Ajax version</a>
</div>

</body>

</html>