<div class="sidenav">
			<h1><? echo $this->_('System'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'system', 'action' => 'index', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Return'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'system', 'action' => 'update', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Update Database'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'system', 'action' => 'update_tree', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Update Tree'); ?></a></li>
			</ul>
			</ul>
			<h1><? echo $this->_('Module'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Install'); ?></a></li>
			</ul>
			<h1><? echo $this->_('Domain'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'domain', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'domain', 'action' => 'add', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Add'); ?></a></li>
			</ul>
			<h1><? echo $this->_('Site'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'add', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Add'); ?></a></li>
			</ul>
			<h1><? echo $this->_('Database'); ?></h1>
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'database', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('List'); ?></a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'database', 'action' => 'add', 'ext' => 'phtml'), 'ext', true); ?>"><? echo $this->_('Add'); ?></a></li>
			</ul>
			<br />
			<br />
			<br />
</div>