<?php
$this->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href'=> $this->path . '/stylesheets/indigo.css'));
$this->headScript(Zend_View_Helper_HeadScript::FILE, $this->path . '/javascripts/jimw.js');
$this->headTitle()->prepend($this->request->getDomainName (). ' - Administration');
if (JIMW_UTF8) $this->headMeta('text/html; charset=utf-8', 'Content-Type', 'http-equiv');
if (isset($this->tree->menutitle))
    $this->headTitle()->append(' - ' . $this->tree->menutitle);
echo $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT);
?>
<html>
<head>
<?php echo $this->headTitle()."\n"; ?>
<?php echo $this->headMeta()."\n"; ?>
<?php echo $this->headLink()."\n"; ?>
<?php echo $this->headStyle()."\n"; ?>
<?php echo $this->headScript()."\n"; ?>
</head>

<body>
	<div class="toolbar">
		<div class="toolbar_left"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'format' => 'phtml'), 'format', true) ?>"><?= $this->_('Intro'); ?></a>
		&nbsp;&nbsp;<a href="<?php echo $this->url(array(), 'format', true, false) ?>" target="_blank"><?php echo $this->_('View site'). ' ' . $this->site->name; ?></a>
		<?php echo $this->_('Others sites'); ?>&nbsp;:
		<?php
        $sites = new Jimw_Site_Site();
        $list = $sites->fetchAll();
        foreach ($list as $site) {
            if ($this->site->id != $site->id)
            echo '&nbsp;&nbsp;<a href="'. $this->url(array('site' => $site->id), 'format') .'" target="_blank">'. $site->name .'</a>';
        }
		?>
		</div>
		<div class="toolbar_right">
		<?php
        if ($this->hasAuth()) {
    		$auth = Zend_Auth::getInstance();
    		$user = $auth->getStorage()->read();
    		echo $this->_('Hello'), ' ', $user->user_firstname, ' ', $user->user_lastname;
        }
		 ?>&nbsp;<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'format' => 'phtml'), 'format', true) ?>"><?php echo $this->_('Logout'); ?></a></div>
	</div>
<div class="container">
	<div class="header">
		<div class="title">
			<h1><?php echo $this->request->getDomainName (); ?> - Administration</h1>
		</div>
		<div class="navigation">
			<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'format' => 'phtml'), 'format', true) ?>"><?php echo $this->_('Intro'); ?></a>
			<a href="<?php echo $this->url(array('controller' => 'tree', 'action' => 'list', 'format' => 'phtml'), 'format', true) ?>"><?php echo $this->_('Pages'); ?></a>
			<a href="<?php echo $this->url(array('controller' => 'file', 'action' => 'index', 'format' => 'ajax'), 'format', true) ?>"><?php echo $this->_('Files'); ?></a>
			<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index', 'format' => 'phtml'), 'format', true) ?>"><?php echo $this->_('Users'); ?></a>
			<a href="<?php echo $this->url(array('controller' => 'system', 'action' => 'index', 'format' => 'phtml'), 'format', true) ?>"><?php echo $this->_('System'); ?></a>
			<div class="clearer"><span></span></div>
		</div>
	</div>
	<div class="main">
<div class="content">
			<?php echo $this->layout()->content; ?>
</div>
<?php
	switch ($this->request->getControllerName()){
		case 'system':
		case 'module':
		case 'domain':
		case 'site':
		case 'database':
			echo $this->render('system/menu.phtml');
			break;
		case 'user':
		case 'group':
		case 'perm':
			echo $this->render('user/menu.phtml');
			break;	}
?>
		<div class="clearer"><span></span></div>
	</div>
</div>
<div class="footer">&copy; 2006-2008 <a href="http://www.jimw.fr">JIMW</a> /
<a href="http://www.logisim.fr" target="_blank">Simon LEPRINCE</a> /
<a href="http://www.lesgrumels.fr" target="_blank">lesgrumels</a>. Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a href="http://validator.w3.org/check?uri=referer">XHTML</a>. Template design by <a href="http://arcsin.se">Arcsin</a>. <a href="<?php echo $this->request->getBaseUrl() ?>/">AJAX version</a>
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>