<?php
	$this->declareVars(array('can_download' => true));
?>
<p>
<?= (isset($this->tree->description))? $this->tree->description:''; ?>
</p>
<script language="Javascript" src="<?php echo $this->path ?>/mootools.v1.11.js" type="text/javascript"></script>
<script language="javascript" src="<?php echo $this->path ?>/gallery/gallery.js" type="text/javascript"></script>
<a name="top"></a>
<div id="photo_titre"></div>
<div><span id="photo_prev"></span>
<span id="photo_next"></span>
</div>
<div id="photo_image"></div>
<div id="photo_loading"></div>

<br />
<?php
	if ($this->can_download):
?>
<form method="post" action="<?php echo $this->request->getBaseUrl() . '/'. $this->tree->alias . '.pzip'; ?>">
<div>
<input type="hidden" name="dir" value="<?php echo $this->photos_path ?>" />
<div id="download_link"><a href="#" onclick="display_download();">Télécharger les photos</a></div>
<?php
	endif;
?>
<br />
<?php
	$i = 0;
	foreach ($this->photos as $photo):
?>
<a href="#top" onclick="display_picture(<?php echo $i++; ?>);">
<img src="<?php echo $photo['thumbnails']; ?>" width="<?php echo $photo['thumbnails_width']; ?>" height="<?php echo $photo['thumbnails_height']; ?>" title="<?php echo $photo['title']; ?>" alt="<?php echo $this->escape($photo['title']); ?>" class="no-border" />
</a>
<?php
	if ($this->can_download):
?>
<span class="download_hidden"><input type="checkbox" name="files[]" value="<?php echo $photo['file']; ?>" class="check"/></span>
<?php
	endif;
?>
<?php
	endforeach;
?>
<script type="text/javascript">
<?php
	$pict = '';
	foreach ($this->photos as $photo) {
		$pict .= '{"url":"'.$photo['url'] . '","title":"'.$photo['url'] . '"},';
	}
	echo 'var image = [', trim($pict, ','), '];';
?>
</script>
<?php
	if ($this->can_download):
?>
<div id="download_button" class="download_hidden">
<a href="#" onclick="select_all();">tous</a>
<input type="submit" value="Télécharger" /></div>
</div>
</form>
<?php
	endif;
?>