	<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th style="width:16px">&nbsp;</th>
			<th style="width:150px"><?php echo $this->_('Name') ?></th>
			<th style="width:150px"><?php echo $this->_('Author') ?></th>
			<th style="width:60%"><?php echo $this->_('Comment') ?></th>
			<th style="width:40px"><?php echo $this->_('Version') ?></th>
			<th style="width:40px" align="right"><?php echo $this->_('Activate') ?></th>
		</tr>
	</thead>
	<?php
		foreach ($this->modules_list as $module): ?>
		<tr>
			<td>
			<img src="<?php echo $this->path ?>/images/icons/module/<?php
				echo (is_readable('./public/images/icons/module/' . $module['path'] . '.png')) ? $module['path'] : 'article';
				?>.png" width="16" height="16" alt="" border="0"/>
			</td>
			<td>
			<?php echo $this->escape($module['name']); ?>
			</td>
			<td><?php echo $this->escape($module['author']); ?></td>
			<td><?php echo $this->escape($module['comment']); ?></td>
			<td><?php echo $this->escape($module['version']); ?></td>
			<td align="right">
				<?php if ($module['activ']): ?>
				<a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'disable', 'ext' => 'phtml', 'id' => $module['id']), 'ext', true); ?>"
				onclick="return confirm('<?php echo $this->escape($this->_('Do you really want to disable this module ? If some page work with this module, they did\'nt work')); ?>');">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Disable') ?>" alt="<?php echo $this->_('Disable') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/accept.png"/>
				</a>
				<?php else: ?>
				<a href="<?php echo $this->url(array('controller' => 'module', 'action' => 'enable', 'ext' => 'phtml', 'module_path' => $module['path']), 'ext', true); ?>">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Enable') ?>" alt="<?php echo $this->_('Enable') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/cross.png"/>
				</a>
				<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
<a href="<?php echo $this->url(array('controller' => 'system'), 'ext', true); ?>"><?php echo $this->_('Return'); ?></a>