<script type="text/javascript" src="<?= $this->path ?>/fckeditor.js"></script>
<form action="<?= $this->request->getBaseUrl() ?>/article/manage/save/id/<?= $this->id ?>" method="post">
<input type="hidden" name="id" value="<?= $this->id ?>">
<table border="0" width="90%" align="right">
<tr><td class="t01">Content : </td><td><textarea name="content" rows="20" cols="60"><?= $this->content ?></textarea></td></tr>
<tr><td colspan="2" align="center"><input type="submit" name="btn" value="Save"></td></tr>
</table></form>
<br/>
<p class="t01" style="font-size: 12px;">
	<a href="<?= $this->request->getBaseUrl() ?>">Return</a>
</p>
<script type="text/javascript">
      window.onload = function()
      {
        var oFCKeditor = new FCKeditor( 'content' ) ;
        oFCKeditor.BasePath = "<?= $this->path ?>/" ;
        oFCKeditor.Width = 600;
		oFCKeditor.Height = 400;
        oFCKeditor.ReplaceTextarea() ;
      }
</script>