<?php echo (!empty($this->tree->description)) ? '<p>' . $this->tree->description . '</p>' : ''; ?>
<?php if (count($this->messages) > 0): ?>
    <?php foreach ($this->messages as $message):
        $comments = $message->getFirstComments(10);
        $form = clone $this->form;
        $form->setAction($this->view->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'add', 'format' => 'phtml', 'alias' => $message->tree_alias), 'format'));
        $form->populate(array('blogmessage_id' => $message->id))
     ?>
          <a name="<?php echo $message->id ?>"></a>
          <h3><a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $message->tree_alias, 'mid' => $message->id), 'format') ?>" class="readmore"><?php echo $message->title ?></a></h3>

          <?php if (!empty($message->header)): ?>
            <p><?php echo $message->header; ?></p>
          <?php else: ?>
            <p><?php echo $message->content; ?></p>
         <?php endif; ?>
         <p class="post-footer align-right">
                <?php echo $this->_('In'), '&nbsp;'; ?><a href="<?php echo $this->url(array('format' => 'phtml', 'alias' => $message->tree_alias), 'alias') ?>" class="readmore"><?php echo $messagetree->tree_menutitle; ?></a>
         
          	    <?php if (!empty($message->header)): ?><a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $message->tree_alias, 'mid' => $message->id), 'format') ?>" class="readmore"><?php echo $this->_('Read more...'); ?></a><?php endif; ?>
          	    <?php if (!empty($message->tree_id)):
                    $treetable = new Jimw_Site_Tree();
                    $messagetree = $treetable->find($message->tree_id)->current();
          	    ?>
          	    <a href="<?php echo $this->url(array('format' => 'phtml', 'alias' => $messagetree->alias), 'alias') ?>" class="readmore"><?php echo $this->_('See more (%s)...', $messagetree->menutitle); ?></a>
          	    <?php endif; ?>
		<?php if ($this->tree->param->comment && $message->comment): ?>
          <?php if (count($comments) > 0): ?>
            <a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $message->tree_alias, 'mid' => $message->id), 'format'); ?>" onclick="javascript:el = document.getElementById('comments<?php echo $message->id ?>'); el.style.display=(el.style.display=='none') ? 'block':'none'; return false;" class="comments"><?php echo $this->_('%d Comments', $comments->getTotalItemCount()); ?></a>
          <?php  else: ?>
            <a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'add', 'format' => 'phtml', 'alias' => $message->tree_alias, 'blogmessage_id' => $message->id), 'format'); ?>" onclick="javascript:el = document.getElementById('addcomment<?php echo $message->id ?>'); el.style.display=(el.style.display=='none') ? 'block':'none'; return false;" class="comments"><?php echo $this->_('Add comment'); ?></a>
          <?php endif; ?>
        <?php endif; ?>
          <span class="date"><?php echo $this->date($message->date); ?></span>
         </p>
        <?php if ($this->tree->param->comment && $message->comment): ?>
         <?php if (count($comments) > 0): ?>
         	<div class="post-footer" id="comments<?php echo $message->id; ?>" style="display: none">
        	<?php foreach($comments as $comment): ?>
          	  <p>
          	  	<small><b><?php echo $this->_('By %1$s the %2$s', $comment->username, $this->date($comment->date)); ?></b><br />
          	      <?php echo nl2br($comment->content); ?>
          	    </small>
          	  </p>
            <?php endforeach; ?>
            <?php if ($comments->getCurrentItemCount() < $comments->getTotalItemCount()): ?>
			<div id="labelnextcomment<?php echo $message->id ?>">
            	<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'message', 'action' => 'view', 'format' => 'phtml', 'alias' => $message->tree_alias, 'mid' => $message->id), 'format') ?>"><?php echo $this->_('Next comments'); ?> &nbsp;&gt;&gt;</a>
            </div>
            <?php endif; ?>
            <div id="labeladdcomment<?php echo $message->id ?>">
            	<a href="<?php echo $this->url(array('module' => 'blog', 'controller' => 'comment', 'action' => 'add', 'format' => 'phtml', 'alias' => $message->tree_alias, 'blogmessage_id' => $message->id), 'format'); ?>" onclick="javascript:el = document.getElementById('addcomment<?php echo $message->id ?>'); el.style.display=(el.style.display=='none') ? 'block':'none'; return false;" class="comments"><?php echo $this->_('Add comment'); ?></a>
            </div>
           	<div id="addcomment<?php echo $message->id ?>" style="display: none;">
                <?php echo $form; ?>
        	</div>
        </div>
        <?php else: ?>
        	<div id="addcomment<?php echo $message->id ?>" style="display: none;">
                <?php echo $form; ?>
        	</div>
        <?php endif; ?>
       <?php endif; ?>
   <?php endforeach; ?>
   <br />
   <?php
echo $this->messages; //Print the pagination control
   ?>
<?php else: ?>
<p><?php echo $this->_('There are yet any message.') ?></p>
<?php endif; ?>
