<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<meta name="Description" content="Site du Rassemblement National des Témoins Aujourd'hui (RNTA) du Mouvement Eucharistique des Jeunes (MEJ) à Lyon" />
<meta name="Keywords" content="mej,lyon,rn,rassemblement,jeunes,témoins" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="Distribution" content="Global" />
<meta name="Author" content="Simon LEPRINCE - JesusWay.fr" />
<meta name="Robots" content="index,follow" />

<link rel="stylesheet" href="<?= $this->path ?>/images/rn2007.css" type="text/css" />
<title>RN TA/ES 2007 - <?= $this->tree->pagetitle; ?></title>
</head>

<body>
<!-- wrap starts here -->
<div id="wrap">

	<!-- content-wrap starts here -->
	<div id="content-wrap">

		<img src="<?= $this->path ?>/images/banner.gif" width="967" height="138" alt="RN TA ES Lyon 2007 : Avec Lui, tu peux faire de TA vie des annéES de lumière !" class="no-border" />

		<div id="sidebar" >

			<!-- <h1>Menu</h1> -->
			<ul class="sidemenu">
				<?php
				/**foreach ($this->menu('left') as $menuitem) {
				?>
				<li>
					<a href="<?php echo $menuitem->toUrl (); ?>"<?php echo ($menuitem->getActive() ? ' class="current"' : ''); ?>><?php echo $menuitem->menutitle; ?></a>
				</li>
				<?php
				if ($menuitem->getExpanded() && $menuitem->hasChildren ()):
				?>
					<ul>
					<?php
					foreach ($menuitem->getChildren() as $submenuitem) {
					?>
						<li>
							<a href="<?php echo $submenuitem->toUrl (); ?>"<?php echo ($submenuitem->getActive() ? ' class="current"' : ''); ?>><?php echo $submenuitem->tree_menutitle; ?></a>
						</li>
					<?php
					}
					?>
					</ul>
				<?php endif;
					}*/
				?>
			<?php
				echo $this->menu('left', array('ulClassName' => 'sidemenu', 'currentClassName' => 'current',
				'menuDepth' => 3, 'menuExpanded' => true));
			?>
			</ul>

			<!--
			<h1>Photos</h1>
			<ul class="sidemenu">

			</ul>
			-->
			<!-- <h1>RNTA</h1>
			<p>&quot;Rassemblement National des T&eacute;moins Aujourd'hui&quot;</p>

			<p class="align-right"><a href="http://www.mej.fr/">MEJ</a></p>	-->

		</div>

		<div id="main">

		<?php echo $this->getContent(); ?>

		</div>

	<!-- content-wrap ends here -->
	</div>

<!-- footer starts here -->
<div id="footer">

	<div class="footer-left">
		<p class="align-left">
		&copy; 2007 <a href="http://www.mej.fr/"><strong>MEJ</strong></a> | <a href="http://www.jesusway.fr/"><strong>JesusWay.fr</strong></a>
		&nbsp; <a href="http://validator.w3.org/check/referer">XHTML</a> |
		<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> valides
		</p>
	</div>

	<div class="footer-right">
		<p class="align-right">
			<a href="/">Accueil</a>&nbsp;|&nbsp;<a href="/admin/">Accès rédacteur</a>
		</p>
	</div>

</div>
<!-- footer ends here -->

<!-- wrap ends here -->
</div>

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-2602870-2";
urchinTracker();
</script>
</body>
</html>