	<h1><img width="16" height="16" border="0" title="<?php echo $this->_('Domain') ?>" alt="<?php echo $this->_('Domain') ?>" class="folder" border="0" src="<?php echo $this->path; ?>/images/icons/world.png"/>&nbsp;<?php echo $this->_('Domain') ?></h1>
	<table cellpadding="0" cellspacing="0" class="list">
	<thead>
		<tr>
			<th style="width:16px">&nbsp;</th>
			<th style="width:60%"><?php echo $this->_('Name') ?></th>
			<th style="width:150px"><?php echo $this->_('Site') ?></th>
			<th style="width:40px" align="right"><?php echo $this->_('Action') ?></th>
		</tr>
	</thead>
	<?php
		foreach ($this->domains_list as $domain): ?>
		<tr>
			<td>
			<?php echo $this->escape($domain->id); ?></td>
			<td>
			<?php echo $this->escape($domain->__toString ()); ?>
			</td>
			<td>
			<?php echo $this->escape($domain->site_id); ?>
			</td>
			<td align="right">
				<a href="<?php echo $this->url(array('controller' => 'domain', 'action' => 'edit', 'format' => 'phtml', 'id' => $domain->id), 'format', true); ?>">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Edit') ?>" alt="<?php echo $this->_('Edit') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/world_edit.png"/>
				</a>
				<a href="<?php echo $this->url(array('controller' => 'domain', 'action' => 'delete', 'format' => 'phtml', 'id' => $domain->id), 'format', true); ?>"  onclick="return confirm('<?php echo $this->escape($this->_('Do you really want to delete this Domain ?')); ?>');">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Delete') ?>" alt="<?php echo $this->_('Delete') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/world_delete.png"/>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
<br />
<a href="<?php echo $this->url(array('controller' => 'domain', 'action' => 'add', 'format' => 'phtml'), 'format', true); ?>"><?php echo $this->_('Add'); ?></a>
<hr />
<a href="<?php echo $this->url(array('controller' => 'system'), 'format', true); ?>"><?php echo $this->_('Return'); ?></a>