<?php foreach ($this->flashmessenger as $message) echo $message . '<br />'; ?>
	<table cellpadding="0" cellspacing="0" class="list">
	<thead>
		<tr>
			<th style="width:32px">&nbsp;</th>
			<th style="width:200px"><?php echo $this->_('Title') ?></th>
			<th style="width:200px"><?php echo $this->_('Artist') ?></th>
			<th style="width:200px" align="right"><?php echo $this->_('Editor') ?></th>
		</tr>
	</thead>
	<?php
		foreach ($this->albums_list as $album): ?>
		<tr>
			<td>
			<?php echo $this->escape($album->id); ?></td>
			<td>
			<a href="<?= $this->url(array('module' => 'shop', 'controller' => 'song', 'action' => 'list', 'shopalbum_id' => $album->id), 'format'); ?>">
			<?php echo $album->title; ?>
			</a>
			</td>
			<td>
			<?php echo $this->escape($album->artist); ?>
			</td>
			<td>
			<?php echo $this->escape($album->editor); ?>
			</td>
			<td align="right">
				<a href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'album', 'action' => 'edit', 'format' => 'phtml', 'blogmessage_id' => $message->id), 'format', true); ?>">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Edit') ?>" alt="<?php echo $this->_('Edit') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/pencil.png"/>
				</a>
				<a href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'album', 'action' => 'delete', 'format' => 'phtml', 'blogmessage_id' => $message->id), 'format', true); ?>"  onclick="return confirm('<?php echo $this->escape($this->_('Do you really want to delete this message ?')); ?>');">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Delete') ?>" alt="<?php echo $this->_('Delete') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/cross.png"/>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
	<?php
    echo $this->albums_list; //Print the pagination control
   ?>
<br />
<a href="<?php echo $this->url(array('module' => 'shop', 'controller' => 'album', 'action' => 'add', 'tree_id' => $this->tree_id, 'format' => 'phtml'), 'format', true); ?>"><?php echo $this->_('Add'); ?></a>
<hr />
<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'tree', 'action' => 'list'), 'format', true); ?>"><?php echo $this->_('Return'); ?></a>