<?php
$this->headLink(array('rel' => 'stylesheet' , 'type' => 'text/css' , 'href' => $this->path . '/jimw.css'));
$this->headTitle()->prepend($this->request->getDomainName() . ' - Administration');
if (isset($this->tree->menutitle))
    $this->headTitle()->append(' - ' . $this->tree->menutitle);
echo $this->doctype(Zend_View_Helper_Doctype::XHTML1_TRANSITIONAL);
?>
<html>
<head>
<?=$this->headTitle();?>
<?=$this->headMeta();?>
<?=$this->headLink();?>
<?=$this->headStyle();?>
<?=$this->headScript();?>
</head>


<body>
	<div class="toolbar">
		<div class="toolbar_left"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'format' => 'phtml'), 'format', true) ?>"><?= $this->_('Intro'); ?></a>
		&nbsp;&nbsp;<a href="<?php echo $this->url(array(), 'format', true, false) ?>" target="_blank"><?php echo $this->_('View site'). ' ' . $this->site->name; ?></a>
		<?php echo $this->_('Others sites'); ?>&nbsp;:
		<?php
        $sites = new Jimw_Site_Site();
        $list = $sites->fetchAll();
        foreach ($list as $site) {
            if ($this->site->id != $site->id)
            echo '&nbsp;&nbsp;<a href="'. $this->url(array('site' => $site->id), 'format') .'" target="_blank">'. $site->name .'</a>';
        }
		?>
		</div>
		<div class="toolbar_right">
		<?php
        if ($this->hasAuth()) {
    		$auth = Zend_Auth::getInstance();
    		$user = $auth->getStorage()->read();
    		echo $this->_('Hello'), ' ', $user->user_firstname, ' ', $user->user_lastname;
        }
		 ?>&nbsp;<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'format' => 'phtml'), 'format', true) ?>"><?php echo $this->_('Logout'); ?></a></div>
	</div>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
	<tr>
		<td class="bg"><img src="<?=$this->path?>/images/px1.gif" width="1"
			height="1" alt="" border="0"></td>
		<td class="bgleft"><img src="<?=$this->path?>/images/bg_left.gif"
			alt="" width="17" height="16" border="0"></td>
		<td>

		<table border="0" cellpadding="0" cellspacing="0" width="780"
			class="fontop">
			<tr>
				<td>
				<table border="0" cellpadding="0" cellspacing="0" width="780">
					<tr>
						<td align="center" width="150"><img
							src="<?=$this->path?>/images/logo.png" alt="Logo Jimw.fr"
							border="0"></td>
						<td class="title"><?php
    echo $this->request->getDomainName();
    ?> - Administration</td>

						<td align="center" class="citation"></td>

						<td align="right">




						<p><a href="http://validator.w3.org/check/referer"><img
							src="<?=$this->path?>/images/valid_html4.gif"
							alt="Valid HTML 4.0 Transitional" height="15" width="80"
							border="0"></a><br>
						<font style="font-size: 4px;">&nbsp;</font><br>
						<a href="http://jigsaw.w3.org/css-validator/check/referer"><img
							src="<?=$this->path?>/images/valid_css.png" alt="Valid CSS"
							height="15" width="80" border="0"></a><br>
						<font style="font-size: 4px;">&nbsp;</font><br>
						<img src="<?=$this->path?>/images/php.png" alt="PHP" height="15"
							width="80" border="0"><br>
						<font style="font-size: 4px;">&nbsp;</font><br>
						<img src="<?=$this->path?>/images/mysql.gif" alt="MySQL"
							height="15" width="80" border="0"></p>



						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>

		<table border="0" cellpadding="0" cellspacing="0" width="780"
			class="fontop01">
			<tr>
				<td>
				<table border="0" cellpadding="0" cellspacing="0">
					<tr>
						<td>
						<p class="menu01"><a
							href="<?=$this->url(array('controller' => 'index' , 'action' => 'index' , 'format' => 'phtml'), 'format', true)?>"><img
							src="<?=$this->path?>/images/b_go.gif" width="19" height="25"
							alt="" border="0" class="absmiddle">&nbsp;&nbsp;Intro</a></p>
						</td>
						<td>
						<p class="menu01"><a
							href="<?=$this->url(array('controller' => 'tree' , 'action' => 'list' , 'format' => 'phtml'), 'format', true)?>"><img
							src="<?=$this->path?>/images/b_go.gif" width="19" height="25"
							alt="" border="0" class="absmiddle">&nbsp;&nbsp;Pages</a></p>
						</td>
						<td>
						<p class="menu01"><a
							href="<?=$this->url(array('controller' => 'file' , 'action' => 'list' , 'format' => 'phtml'), 'format', true)?>"><img
							src="<?=$this->path?>/images/b_go.gif" width="19" height="25"
							alt="" border="0" class="absmiddle">&nbsp;&nbsp;Files</a></p>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>






		<table border="0" cellpadding="0" cellspacing="0" width="780">
			<tr bgcolor="#AFC0D0" valign="top">
				<td width="487">

	<?php
echo $this->layout()->content;
?>
	</td>
				<td width="2" class="dotsw"><img
					src="<?=$this->path?>/images/px1.gif" alt="" width="1" height="1"
					border="0"></td>
			</tr>
		</table>



		<table border="0" cellpadding="0" cellspacing="0" width="780">
			<tr>
				<td colspan="2"><img src="<?=$this->path?>/images/px1.gif"
					width="1" height="1" alt="" border="0"></td>
			</tr>
			<tr bgcolor="#28549E">
				<td height="19" colspan="2"><img
					src="<?=$this->path?>/images/px1.gif" width="1" height="1" alt=""
					border="0"></td>
			</tr>
			<tr>
				<td height="70">
				<p><a href="<?php
    echo $this->request->getBaseUrl()?>/">AJAX
				version</a><br />Copyright &copy; 2006 - 2008 <?php
    echo $this->request->getDomainName();
    ?> /
<a href="http://www.logisim.fr" target="_blank">Simon LEPRINCE</a> / <a
					href="http://www.lesgrumels.fr" target="_blank">lesgrumels</a></p>
				</td>
				<td></td>
			</tr>
		</table>
		</td>
		<td class="bgright"><img src="<?= $this->path ?>/images/bg_right.gif"
			alt="" width="17" height="16" border="0"></td>
		<td class="bg"><img src="<?= $this->path ?>/images/px1.gif" width="1"
			height="1" alt="" border="0"></td>
	</tr>
</table>
</body>
</html>