<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<meta name="description" content="description"/>
<meta name="keywords" content="keywords"/>
<meta name="author" content="author"/>
<link rel="stylesheet" type="text/css" href="/admin/public/stylesheets/indigo.css" media="screen"/>
<title>Jimw Installation</title>
</head>

<body>
<div class="container">

	<div class="header">

		<div class="title">
			<h1>Installation</h1>
		</div>

		<div class="navigation">
			<a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), 'get', true) ?>"><?= $this->_('Intro'); ?></a>
			<a href="<?= $this->url(array('controller' => 'update', 'action' => 'index'), 'get', true) ?>"><?= $this->_('Update'); ?></a>
			<a href="<?= $this->url(array('controller' => 'site', 'action' => 'list'), 'get', true) ?>"><?= $this->_('Sites'); ?></a>
			<a href="<?= $this->url(array('controller' => 'system', 'action' => 'index'), 'get', true) ?>"><?= $this->_('System'); ?></a>
			<a href="<?= $this->url(array('controller' => 'install', 'action' => 'configuration'), 'get', true) ?>"><?= $this->_('Configuration'); ?></a>
			<div class="clearer"><span></span></div>
		</div>

	</div>

	<div class="main">

<div class="content">
			<?php echo $this->layout()->content; ?>
</div>

		<div class="clearer"><span></span></div>

	</div>

</div>
<br />
<hr />
<div class="footer">&copy; 2006-2008 <a href="http://www.jimw.fr">JIMW</a> /
<a href="http://www.logisim.fr" target="_blank">Simon LEPRINCE</a> /
<a href="http://www.lesgrumels.fr" target="_blank">lesgrumels</a>. Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a href="http://validator.w3.org/check?uri=referer">XHTML</a>. Template design by <a href="http://arcsin.se">Arcsin</a>. <a href="<?php echo $this->request->getBaseUrl() ?>/">AJAX version</a>
</div>

</body>

</html>