<?php
	$this->declareVars(array('can_download' => false));
?>
<p>
<?= (isset($this->tree->description))? $this->tree->description:''; ?>
</p>
<?= $this->headScript()->captureStart(); ?>
var lang_next = '<?=$this->_('Next'); ?>';
var lang_prev = '<?=$this->_('Prev'); ?>';
var lang_loading = '<?=$this->_('Loading...'); ?>';
<?= $this->headScript()->captureEnd(); ?>
<?= $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->path_common . '/mootools.v1.11.js'); ?>
<?= $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->path_common . '/gallery.js'); ?>
<script type="text/javascript" src="js/mootools.js"></script>
<script type="text/javascript" src="js/slimbox.js"></script>
<link rel="stylesheet" href="css/slimbox.css" type="text/css" media="screen" />
<a name="top"></a>
<div id="photo_titre"></div>
<div><span id="photo_prev"></span>
<span id="photo_next"></span>
</div>
<div id="photo_image"></div>
<div id="photo_loading"></div>

<br />
<?php
	if ($this->can_download):
?>
<form method="post" action="<?php echo $this->request->getBaseUrl() . '/'. $this->tree->alias . '.pzip'; ?>">
<div>
<input type="hidden" name="dir" value="<?php echo $this->photos_path ?>" />
<div id="download_link"><a href="#" onclick="display_download();"><?= $this->_('Download pictures'); ?></a></div>
<?php
	endif;
?>
<br />
<?php
	$i = 0;
	foreach ($this->photos as $photo):
/*
<!--   <a href="#top" onclick="display_picture(<?php echo $i++; ?>);">
<img src="<?php echo $photo['thumbnails']; ?>" width="<?php echo $photo['thumbnails_width']; ?>" height="<?php echo $photo['thumbnails_height']; ?>" title="<?php echo $photo['title']; ?>" alt="<?php echo $this->escape($photo['title']); ?>" class="no-border" />
</a>
-->
*/
?>
<a href="<?php echo $photo['url']; ?>" rel="lightbox[picasa]" title="<?php echo addslashes($photo['title']); ?>" >
<img align="center" src="<?php echo $photo['thumbnails']; ?>" width="<?php echo $photo['thumbnails_width']; ?>" height="<?php echo $photo['thumbnails_height']; ?>" title="<?php echo $photo['title']; ?>" border="0">
</a>
<?php
	if ($this->can_download):
?>
<span class="download_hidden"><input type="checkbox" name="files[]" value="<?php echo $photo['file']; ?>" class="check"/></span>
<?php
	endif;
?>
<?php
	endforeach;
?>
<script type="text/javascript">
<?php
	$pict = '';
	foreach ($this->photos as $photo) {
		$pict .= '{"url":"'.$photo['url'] . '","title":"'.$photo['url'] . '"},';
	}
	echo 'var image = [', trim($pict, ','), '];';
?>
</script>
<?php
	if ($this->can_download):
?>
<div id="download_button" class="download_hidden">
<a href="#" onclick="select_all();">tous</a>
<input type="submit" value="<?= $this->_('Download') ?>" /></div>
</div>
</form>
<?php
	endif;
?>