<div class="content">
	<table cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th style="width:16px">&nbsp;</th>
			<th style="width:100px"><?php echo $this->_('Tree') ?></th>
			<th style="width:100px"><?php echo $this->_('Name') ?></th>
			<th style="width:100px"><?php echo $this->_('Access') ?></th>
			<th style="width:150px"><?php echo $this->_('Path') ?></th>
			<th style="width:40px" align="right"><?php echo $this->_('Action') ?></th>
		</tr>
	</thead>
	<?php
		foreach ($this->sites_list as $site): ?>
		<tr>
			<td>
			<?php echo $this->escape($site->id); ?></td>
			<td>
			<?php echo $this->escape($site->tree_id); ?>
			</td>
			<td>
			<?php echo $this->escape($site->name); ?>
			</td>
			<td>
			<?php echo $this->escape($site->access); ?>
			</td>
			<td>
			<?php echo $this->escape($site->path); ?>
			</td>
			<td align="right">
				<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'edit', 'ext' => 'phtml', 'id' => $site->id), 'ext', true); ?>">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Edit') ?>" alt="<?php echo $this->_('Edit') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/pencil.png"/>
				</a>
				<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'delete', 'ext' => 'phtml', 'id' => $site->id), 'ext', true); ?>"  onclick="return confirm('<?php echo $this->escape($this->_('Do you really want to delete this Site ?')); ?>');">
					<img width="16" height="18" border="0" title="<?php echo $this->_('Delete') ?>" alt="<?php echo $this->_('Delete') ?>" class="folder" src="<?php echo $this->path; ?>/images/icons/cross.png"/>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</table>
</div>
<?php echo $this->render('system/menu.phtml'); ?>