<form action="<?php echo $this->url(array('controller' => 'site', 'action' => $this->form_type, 'ext' => 'phtml'), 'ext', true); ?>" method="post">
<input type="hidden" name="id" value="<?= $this->id ?>">
<input type="hidden" name="sub" value="1">
<table border="0" width="90%">
<? if (!empty($this->id)): ?>
<tr><td class="t01"><?php echo $this->_('Id'); ?> :</td><td class="t01"><?= $this->id ?></td></tr>
<? endif; ?>
<tr><td class="t01"><?php echo $this->formLabel('tree_id', $this->_('Tree')); ?> :</td><td><?php echo $this->SelectTree('tree_id', $this->site->tree_id, array()); ?></td></tr>
<tr><td class="t01"><?php echo $this->formLabel('name', $this->_('Name')); ?> :</td><td><?php echo $this->formText('name', $this->site->name); ?></td></tr>
<tr><td class="t01"><?php echo $this->formLabel('access', $this->_('Access')); ?> :</td><td><?php echo $this->formText('access', $this->site->access); ?></td></tr>
<tr><td class="t01"><?php echo $this->formLabel('path', $this->_('Path')); ?> : </td><td><?php echo $this->formText('path', $this->site->path); ?></td></tr>
<tr><td colspan="2" align="center"><?php echo $this->formSubmit('btn', $this->_(ucfirst($this->form_type))); ?></td>
</tr>
</table></form>
<br/>
<p class="t01" style="font-size: 12px;">
<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'list', 'ext' => 'phtml'), 'ext', true); ?>"><?php echo $this->_('Return') ?></a>
</p>