<h1><img width="16" height="16" border="0"
	title="<?php
echo $this->_('Site')?>"
	alt="<?php
echo $this->_('Site')?>" class="folder" border="0"
	src="<?php
echo $this->path;
?>/images/icons/application.png" />&nbsp;<?php
echo $this->_('Site')?></h1>
<?=$this->form;?>
<br style="clear: both;" />
<p style="font-size: 12px;">
<a href="<?php
echo $this->url(array('controller' => 'site' , 'action' => 'list' , 'format' => 'phtml'), 'format', true);
?>" class="jimw-return">
    <?php echo $this->_('Return');?>
</a>
</p>